lib/nylas-connection.js
nylas-connection.coffee

A small PR. Just removing the logging of access token info....

Removing console.logs which pipe out access token info

---

lib/models/restful-model-collection.js
models/restful-model-collection.coffee
package.json
spec/restful-model-collection-spec.coffee

* Fixed restful-model-collection's delete method as it was calling request with wrong params
* Adjusted restful-mode-collection-spec accordingly
* Added missing devDependencies to package.json

Fixed model-collection and tests

---

lib/models/event.js
lib/models/participant.js
models/event.coffee
models/participant.coffee
spec/event-spec.coffee

* Added participant model to be used in the event's participants collection
* Added save method and missing attributes for the event model
* Created event-spec to cover the event model tests

Extended events model to include creating and updating of model

---

lib/nylas.js
nylas.coffee

`state` url parametr - optional arbitrary string that is returned as a URL parameter in a redirect_uri

Missing a `state` url parameter

---

lib/models/message.js
lib/nylas.js
models/message.coffee

'version' attribute should be an integer

---

nylas-connection.coffee
package.json
spec/nylas-connection-spec.coffee

That's handy information to have!

Include User-Agent header in API requests

---

__tests__/account-spec.js
src/models/account.js

Add support for the new `linkedAt` field on the account model

Add linkedAt field to the account model

---

package.json
yarn.lock

Remove express-session from dependencies

---

__tests__/account-spec.js
__tests__/contact-spec.js
__tests__/delta-spec.js
__tests__/draft-spec.js
__tests__/event-spec.js
__tests__/file-spec.js
__tests__/label-spec.js
__tests__/management-account-spec.js
__tests__/message-spec.js
__tests__/nylas-api-spec.js
__tests__/restful-model-collection-spec.js
__tests__/restful-model-spec.js
__tests__/thread-spec.js
package-lock.json
package.json
src/models/delta.js
src/models/draft.js
src/models/event.js
src/models/folder.js
src/models/restful-model-collection.js
src/models/restful-model-instance.js
src/models/restful-model.js
src/nylas-connection.js
src/nylas.js

The Bluebird GitHub project includes [this note](https://github.com/petkaantonov/bluebird/#note):
> Promises in Node.js 10 are significantly faster than before. Bluebird still includes a lot of features like cancellation, iteration methods and warnings that native promises don't. If you are using Bluebird for performance rather than for those - please consider giving native promises a shot and running the benchmarks yourself.
We don't need the extra features that Bluebird provides, so it's probably better to drop this dependency and go for native promises instead.

Native promises

---

__tests__/account-spec.js
__tests__/contact-spec.js
__tests__/delta-spec.js
__tests__/draft-spec.js
__tests__/event-spec.js
__tests__/file-spec.js
__tests__/label-spec.js
__tests__/management-account-spec.js
__tests__/message-spec.js
__tests__/nylas-connection-spec.js
__tests__/restful-model-collection-spec.js
__tests__/restful-model-spec.js
__tests__/thread-spec.js
src/nylas-connection.js
src/nylas.js

Python SDK: https://github.com/nylas/nylas-python/pull/112
Ruby SDK: https://github.com/nylas/nylas-ruby/pull/209

Add X-Nylas-Client-Id header

---

README.md
__tests__/management-account-spec.js
__tests__/message-spec.js
src/models/management-account.js

Add support for revoke-all endpoint

add revoke-all endpoint

---

README.md

See full granular scopes here: https://docs.nylas.com/docs/authentication-scopes

Update readme with granular scopes

---

CHANGELOG.md
README.md
__tests__/draft-spec.js
package-lock.json
package.json
src/models/draft.js

Example for README.md:
```  
Nylas.config({
appId: 'appID',
appSecret: 'appSecret',
});
const nylas = Nylas.with(NYLAS_TOKEN);
const draft = nylas.drafts.build({
"tracking":{
"opens": true
},
"body" : "let's have coffee!",
"subject": "coffee",
"to": [
{
"name": "test",
"email": "test@test.com"
}
],
"from": [
{
"name": "test2",
"email": "test2@test.com"
}
]
});
draft.send().then(message => {
console.log(`${message.id} was sent`);
});
```

Implement message tracking functionality

---

__tests__/contact-spec.js
__tests__/event-spec.js
__tests__/file-spec.js
__tests__/message-spec.js

Brings test coverage from 77.51% to 81.26%

Increase test coverage for files, contacts, event/email participants

---

CHANGELOG.md
__tests__/management-account-spec.js
src/models/management-account.js

add support for `/token-info` endpoint

add token-info endpoint

---

CHANGELOG.md
README.md
__tests__/webhook-spec.js
example/authentication/auth.js
src/models/restful-model-collection.js
src/models/restful-model.js
src/models/webhook.js
src/nylas-connection.js
src/nylas.js

Adds create, read, update and delete functionality for webhooks.

implement webhooks CRUD

---

CHANGELOG.md
package-lock.json

Re-ran `npm install` to generate a new package-lock.json file. The other updates should fix the warnings that appear when running `npm install` too 🤞

update package lock and resolve eslint-utils security warning

---

.travis.yml
package.json

* add test coverage to Travis CI build
* set coverage thresholds to 80 / 80 / 80 (currently 82.93 / 86.67 / 82.99)
* run linter on current version of Node (12)

add code coverage to travis build

---

Contributing.md
README.md
pull_request_template.md

Changes include:
* README.md - Updated to point users toward the Nylas Node SDK Quickstart Guide and all code examples have been moved to this quickstart.
* Contributing.md - Updated to new format. Moved testing information here.
* pull_request_template.md - Implement new PR template that adds license declaration to new PRs.

Implement Standard SDK Format

---

CHANGELOG.md
__tests__/event-spec.js
src/models/event.js
src/nylas-connection.js

Implementing ical_uid and upgrading supported API version re: https://headwayapp.co/nylas-changelog/icaluid-support-132816

add ical_uid to event and upgrade API version

---

.travis.yml

Node 14 was released today: https://nodejs.org/en/about/releases/

test support for node 13 and 14

---

CHANGELOG.md
__tests__/event-spec.js
src/models/event.ts

Support recurring events

---

__tests__/nylas-api-spec.js
src/nylas.ts

Implementing support for application management:
https://docs.nylas.com/reference#list-app-details
https://docs.nylas.com/reference#update-application-details

get and set application details

---

CHANGELOG.md
__tests__/calendar-restful-model-collection-spec.js
__tests__/restful-model-collection-spec.js
src/models/calendar-restful-model-collection.ts
src/nylas-connection.ts

Adding support for the free-busy endpoint: https://docs.nylas.com/reference#calendars-free-busy

add CalendarRestfulModelCollection to implement freebusy

---

src/models/message.ts

Lodash has direct imports everywhere except this case.

Avoid improting whole lodash

---

CHANGELOG.md
__tests__/resource-spec.js
src/models/resource.ts
src/nylas-connection.ts

Re-opening https://github.com/nylas/nylas-nodejs/pull/189 against `main`

support get resources

---

CHANGELOG.md
__tests__/event-spec.js
src/models/event.ts

Add object attribute back to event.when

---

CHANGELOG.md
__tests__/calendar-spec.js
__tests__/job-status-spec.js
src/models/calendar.ts
src/models/job-status.ts
src/nylas-connection.ts

Implementing support for job statuses re: https://docs.nylas.com/reference#job-statuses-1

add job statuses

---

CHANGELOG.md
__tests__/event-spec.js
src/models/event.ts

Conditionally create event.when when setting event.start and event.end

---

README.md
example/authentication/readme.md
example/sample-app/readme.md

Use Javascript (and bash) syntax highlighting in the Markdown file

---

__tests__/calendar-spec.js
__tests__/draft-spec.js
__tests__/file-spec.js
__tests__/label-spec.js
__tests__/message-spec.js
__tests__/restful-model-collection-spec.js
__tests__/restful-model-spec.js
__tests__/thread-spec.js
package-lock.json
package.json

Request package was left in dependencies here https://github.com/nylas/nylas-nodejs/pull/234

Move request to dev dependencies

---

.github/workflows/clubhouse.yml
.github/workflows/pull-reqeust.yml
.github/workflows/test.yml

Added a new workflow to execute tests on new PRs to `main` as well as fixing some issues with the clubhouse action.

[63230] Add new Github action to run test cases

---

__tests__/calendar-restful-model-collection-spec.js
src/models/calendar-restful-model-collection.ts

https://developer.nylas.com/docs/api/#post/calendars/availability

add and test calendars.availability() API

---

CHANGELOG.md
package-lock.json
package.json

New `nylas` v5.7.0 release bringing in the following new features:
* Add missing fields for recurring events (#259, #221)
* Add support for conferencing (#261)
The new release also fixes the following:
* Fix minor issues with Neural API implementation (#257, #258)
* Fix not rejecting uncaught errors during requests (#262, #260)

v5.7.0 Release

---

CHANGELOG.md
package-lock.json
package.json

New `nylas` v5.9.0 release bringing in the following new features:
* Add Component CRUD Support (#282)
* Add Scheduler support (#280)

v5.9.0 Release

---

CHANGELOG.md
package-lock.json
package.json

New `nylas` v5.10.0 release bringing in the following new features:
* Add support for Event notifications (#285)
* Add support for remaining Scheduler endpoints (#287)
* Add metadata support for `Calendar`, `Message` and `ManagementAccount` (#286, #288)

v5.10.0 release

---

CHANGELOG.md
__tests__/component-spec.js
__tests__/scheduler-spec.js
src/models/component.ts
src/models/scheduler.ts

A couple of Scheduler and Component types were incorrect or missing. This PR also ensures modifiable fields are not sent when trying to update a component.

[75337] Fix Scheduler and Component types

---

__tests__/folder-spec.js

Adding test coverage for folders.

[76798] Add tests for `Folder`

---

CHANGELOG.md
package-lock.json
package.json

New `nylas` v6.2.0 release provides the following new features:
* Add support for returning multiple messages by a list of message IDs (#317, #313)
* Add new field in `Draft` for adding files by file IDs (#319, #314)
* Add Webhook Notification models (#320, #311)
and the following improvements:
* Improved `Delta` support: added `Delta` model and two new methods; `since` and `longpoll` (#316)
* Fix Virtual Calendar logic and serialization (#318)

v6.2.0 Release

---

__tests__/outbox-spec.js
src/models/outbox-job-status.ts
src/models/outbox-message.ts
src/models/outbox.ts
src/nylas-connection.ts

This PR brings support to the [new outbox beta](https://developer.nylas.com/docs/api#tag--Outbox).
To send a new message through the outbox:
```javascript
// Create a new draft
const draftProps = {
subject: 'With Love, from Nylas',
to: [{ name: 'Me', email: "me@email.com" }],
body: 'This email was sent using the Nylas email API. Visit https://nylas.com for details.'
}
const draft = new Draft(nylas, draftProps);
// Prepare the outbox-specific parameters
const today = new Date()
const tomorrow = new Date(today)
tomorrow.setDate(tomorrow.getDate() + 1)
const dayAfter = new Date(tomorrow)
dayAfter.setDate(dayAfter.getDate() + 1)
// Send the outbox …
```

[TDSK-96] Outbox Support

---

CHANGELOG.md
__tests__/calendar-restful-model-collection-spec.js
__tests__/event-spec.js
src/models/event.ts
src/models/free-busy.ts
src/models/scheduler.ts

This PR bring support to [collective](https://developer.nylas.com/docs/connectivity/calendar/calendar-availability/#collective-meetings) and [group events](https://developer.nylas.com/docs/connectivity/calendar/calendar-availability/#group-meetings).

[TSDK-296] Support collective and group events

---

src/models/event.ts

https://nylas.atlassian.net/browse/CUST-919

Add reminder_minutes

---

src/server-bindings/express-binding.ts
src/server-bindings/server-binding.ts

Add config parameter for server bindings to be able to automatically create websocket webhook connection

Tunnel express automatically for v7.0.0

---

CHANGELOG.md
package-lock.json
package.json
src/server-bindings/express-binding.ts

The user will have to enable cors on their main app anyways and we shouldn’t be dictating generalized opinions. The user should be in control here.

Remove cors from server bindings

---

.github/workflows/pull-reqeust.yml
README.md
package.json

Add codecov support

---

__tests__/express-binding-spec.js
__tests__/nylas-api-spec.js
__tests__/routes-spec.js

This PR adds test coverage to our new features ahead of the v7 beta 1 release.

Add unit tests for server bindings and middleware routes

---

.github/workflows/pull-reqeust.yml
CHANGELOG.md
README.md
__tests__/event-spec.js
__tests__/job-status-spec.js
__tests__/scheduler-spec.js
package.json
src/models/event-participant.ts
src/models/event.ts
src/models/job-status.ts
src/models/scheduler.ts

This PR cherry picks the diff commits from main and the v7 branch to ensure beta 1 has all the up to date features and bugfixes

Backport v6.5.0 and v6.5.1 features to v7 branch

---

CHANGELOG.md
package-lock.json
package.json

v6.7.0 Release

---

CHANGELOG.md
package-lock.json
package.json
src/config.ts
src/models/webhook.ts
src/services/tunnel.ts

This PR enables support for local webhook development. When implementing this feature in your app, the SDK will create a tunnel connection to a websocket server and registers it as a webhook callback to your Nylas account.
During the setup process you can pass in methods to override the websocket client's callback methods. The most important method is the `onMessage` method which returns a parsed delta event from the webhook server.
```js
const { openWebhookTunnel } = require('nylas/lib/services/tunnel');
// Initialize an instance of the Nylas SDK using the client credentials
Nylas.config({
clientId: "CLIENT_ID",
clientSecret: "CLIENT_SECRET",
});
// Define the callback for the onMessage event
const onMessageListener = (delta) => {
if(delta.type === …
```

Local webhook testing support

---

src/apiClient.ts
src/resources/baseResource.ts
src/resources/calendars.ts
src/resources/events.ts
src/schema/calendars.ts
src/schema/error.ts
src/schema/events.ts
src/schema/request.ts
src/schema/response.ts

Av 681 av 680 av 679 av 543 av 407 av 410 av 539 av 540 av 541 av 542 av 538 av 537 av 536

---

src/apiClient.ts
src/nylas.ts
src/resources/auth.ts
src/schema/auth.ts
src/schema/error.ts
src/schema/response.ts

Auth methods for SDK for generating hosted auth links (`code` or `adminconsent`), code exchange handling, token exchange handling & revoking tokens

Hosted auth

---

src/apiClient.ts
src/resources/baseResource.ts
src/resources/calendars.ts
src/resources/events.ts
src/resources/grants.ts
src/resources/webhooks.ts
src/schema/response.ts
src/schema/webhooks.ts

The API was returning 204 for DELETE calls, now it returns 200 with a body.

Delete returns 200 instead of 204 now

---

src/resources/auth.ts
src/schema/auth.ts

Added hosted auth

---

src/schema/calendars.ts
src/schema/events.ts

This PR just provides updates to the fields for the Event schema and its subschemas, and also fixing the types and addressing todos.

Update Event schema and subschemas

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/models/calendars.ts
src/models/webhooks.ts
src/resources/calendars.ts
src/resources/webhooks.ts

This PR is for releasing the first beta of v7 on npm.

v7.0.0-beta.1 Release

---

README.md
UPGRADE.md

This PR adds an upgrade doc for the Node SDK.

Add UPGRADE file

---

CHANGELOG.md
src/models/freeBusy.ts
src/resources/calendars.ts

This PR adds support for the free busy endpoint.

Add Free-Busy Support

---

src/models/drafts.ts
src/models/messages.ts
src/resources/messages.ts

This PR includes `from` and `schedule_id` to the Message type
JIRA: https://nylas.atlassian.net/browse/TSDK-596?atlOrigin=eyJpIjoiM2JiZGVhMDFlOTAzNGYyYzg5MzViYjE0YmM3M2I1NTciLCJwIjoiaiJ9

Adding from and scheduled_id to message schema

---

src/models/events.ts

https://nylas.atlassian.net/browse/TSDK-599?atlOrigin=eyJpIjoiODljZDc1NzQwYzM1NGJkNWJjNjVlNGI1MjExNzI1ZDkiLCJwIjoiaiJ9

Change reminderMinutes to a number instead of a string

---

CHANGELOG.md
src/models/events.ts

- Adding masterEventID to Event class.
- Add 

Add support for masterEventId on Event class

---

CHANGELOG.md
src/models/grants.ts
src/models/listQueryParams.ts

- Added missing `select` field (https://github.com/nylas/nylas-nodejs/issues/581)
- Added missing `name` field (https://github.com/nylas/nylas-nodejs/issues/599)

Add missing fields

---

CHANGELOG.md
src/models/events.ts

- Add missing `masterEventID` on Event model

Add missing masterEventId on event model

---

CHANGELOG.md

- Add missing `select` field on query params (#600)
- Add missing `name` field on grant model (#600)
- Add missing `masterEventId` on Event model (#601)
- Fix for the webhook rotate secret calling the wrong endpoint (#596, #597 )

7.6.2 Release

---

CHANGELOG.md
src/resources/messages.ts

- Fixed the issue where inline attachments > 3Mb were not sent correctly. 

Fix inline attachments > 3MB to sent correctly.

---

CHANGELOG.md

* Fix query parameters for array values (#606)

v7.7.1 Release

---

src/resources/credentials.ts
tests/resources/credentials.spec.ts

- Fix credentials resource to use correct endpoint
- https://github.com/nylas/nylas-nodejs/issues/605

Fix Credentials endpoint

---

.cursor/rules/nylas-nodejs-sdk-rules.mdc
examples/notetakers/notetaker.ts
src/models/notetakers.ts
tests/resources/notetakers.spec.ts

fix: update notetaker media endpoint to support media download

---

CHANGELOG.md
src/models/availability.ts
src/models/events.ts
tests/resources/calendars.spec.ts
tests/resources/events.spec.ts

Add tentative_as_busy parameter
