nylas/nylas-nodejs

- README.md
- lib/models/delta.js
- lib/models/namespace.js
- lib/nylas-connection.js
- models/delta.coffee
- models/namespace.coffee
- nylas-connection.coffee
- package.json
- spec/delta-spec.coffee
@bengotow 
- New `namespace.delta` to expose delta API
- `namespace.delta.generateCursor(timestampMs, [callback])` to get a Nylas delta cursor from a C-like timestamp
- `namespace.delta.startStream(cursor, excludeTypes = [])` to initiate a delta streaming API connection. It returns a `DeltaStream` which emits `response`, `delta`, and `error` events.
- Jasmine tests for delta streaming, covering:
- Starting and closing a stream
- Parsing the streaming response into JSON objects
- Handling JSON objects broken into multiple data packets
- Automatically restarting the connection after a timeout not receiving any data (normally the Nylas server sends a heartbeat every second on the streaming connection)
- NylasConnection updates
- NylasConnection now clones the passed-in options and adds the …
> Add delta streaming API support

- README.md
Fix Documentation on Delta Streaming Endpoint where callback has two arguments: error, cursor.
> Update Delta Streaming Endpoint Example in README

- lib/models/calendar.js
- models/calendar.coffee
Noticed that the calendar model wasn't exposing the read_only property from the response json. This is very essential to determine if you can create an event to a calendar, so I added it.
> Fixed calendar model not exposing readOnly state of a calendar

- lib/models/event.js
- lib/models/restful-model-collection.js
- models/event.coffee
- models/restful-model-collection.coffee
- spec/event-spec.coffee
- spec/restful-model-collection-spec.coffee
Added ability to pass in params to the event.save method in order to use them as a query-string value in the url. I followed similar implementation from restful-model-collection with the exception that I made the params optional. This way it also retains the backwards compatibility.
Also added tests for this feature.
> Add params to event.save method

- README.md
- lib/models/delta.js
- models/delta.coffee
- spec/delta-spec.coffee
@bengotow 
Bunch of small fixes to delta streaming API:
- Clear timeouts when calling `stream.close()` explicitly so the stream doesn't auto-restart in that case
- Add test for ensuring no auto-restart on explicit close
- Fix the auto-restart test, which failed due to bumping up the timeouts in commit d37708327ebd7e809e063a3f8b34fa7a9df13598
Unrelated, I also added missing err params to callbacks in README.md.
> Delta streaming - don't auto-restart when connection is explicitly closed

- lib/models/delta.js
- lib/nylas.js
- nylas.coffee
- spec/nylas-api-spec.coffee
Looking at the Nylas API docs, the oauth enpoint has changed to `https://api.nylas.com`
Edit: Signed the CLA
> Update Server Side Auth Endpoint

- lib/models/delta.js
- models/delta.coffee
- spec/delta-spec.coffee
@khamidou 
It seems like the Nylas server has recently changed to send heartbeats on the streaming delta connection only every 5 seconds, increased from every 1 second. This client library happens to have been configured to time out and reconnect after 5 seconds with no heartbeat.
Things do still work. However, that's more requests to the Nylas server than needed, plus it results in a lot of log spam.
This PR:
- Increases the default reconnect timeout to 15 seconds, up from 5 seconds. (2-3 missed 5s heartbeats, instead of 4-5 missed 1s heartbeats)
- Puts the reconnect timeout onto `Delta. streamingTimeoutMs` so it can be changed by clients in the future without needing to change this library.
- Reduces internal logging on reconnects to only log the URL, instead of the entire DeltaStream …
> Bump delta stream reconnect timeout to 15s, reduce verbosity of reconnect logging

- models/delta.coffee
- models/restful-model-collection.coffee
- models/restful-model-instance.coffee
- models/thread.coffee
- nylas-connection.coffee
- spec/account-spec.coffee
- spec/delta-spec.coffee
- spec/nylas-connection-spec.coffee
- spec/restful-model-collection-spec.coffee
- spec/thread-spec.coffee
Currently, for all methods on `RestfulModelCollection` except `find`,
users can manually pass `{view: 'expanded'}` as parameter.
This commit allows request params to be passed to `RestfulModelCollection::find`
and `RestfulModelInstance::get` too, so users can pass any params they
want when fetching individual models.
Additionaly, updates nylas-connection to support the option `expanded: true`
for all requests and transforms it to `view: 'expanded'` for convenience
> Add option to support view=expanded api param

- src/nylas.coffee
To enable client side usage without leaking or faking the app secret
> don't require secret for urlForAuthentication

- lib/models/restful-model-collection.js
- lib/models/thread.js
- lib/nylas-connection.js
- src/models/restful-model-collection.coffee
closes #56 
Errors thrown inside the range method (`RestfulModelCollection.prototype.range`) do not get returned back to the list method.
Added a catch statement to this so that it will work properly.
I am not sure why there are changes to the `lib/models/thread` file (they were made when I ran the default `grunt` command). If this is undesired I can modify the PR so just let me know.
> add catch statement to range method in restful-model-collection

- lib/models/delta.js
- src/models/delta.coffee
This shouldn't be logging to console if it's an `EventEmitter`.
> Refactor: Use event to emit DeltaStream retry status

- src/nylas-connection.js
Summary: Add response status code to the error. This fixes the issue of the status code being swallowed and allows it to bubble up to the consumer.
Test Plan: manual
Reviewers: evan, halla
Differential Revision: https://phab.nylas.com/D6398
> Add status code to error handling

- src/nylas-connection.js
Our code has a warning for when the api version that the application is using and the api version that the sdk supports are mismatched. Initially, we had a version agnostic warning for when the versions were mismatched. This warning could show even when a version was missing and there were complaints that it was spamming the console without being helpful. It could be the case that the versions are the same, however the application just has not sent its api version and because it is null, this warning will show.
This commit makes it so a warning only displays if both the api version and the sdk version are present. 
Resolves #72
> Move warning to print only if both sdk version and api version exist

- src/nylas-connection.js
This commit adds a check for if the body is a string, and if so converts it to JSON. Originally, we were just doing the conversion in the case that it was not an error. @jylauril suggested adding it to the error case to enable `error.message` to actually work.   I moved this conversion outside the if/else because it is necessary in both cases. 
Fixes #69
> Parse body into JSON if its a string

- .babelrc
- .eslintrc
- __tests__/draft-spec.js
- __tests__/event-spec.js
- __tests__/file-spec.js
- __tests__/label-spec.js
- __tests__/management-account-spec.js
- __tests__/message-spec.js
- __tests__/nylas-connection-spec.js
- __tests__/restful-model-spec.js
- __tests__/thread-spec.js
- package.json
- src/models/account.js
- src/models/calendar.js
- src/models/contact.js
- src/models/delta.js
- src/models/draft.js
- src/models/email-participant.js
- src/models/event-participant.js
- src/models/event.js
- src/models/file.js
- src/models/folder.js
- src/models/management-account.js
- src/models/message.js
- src/models/restful-model-collection.js
- src/models/thread.js
- src/nylas-connection.js
- src/nylas.js
- yarn.lock
We can use [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) to replace `_.extend()`, and make the code clearer as well.
> ES6 object spread

- package.json
- src/models/delta.js
- src/models/message.js
- src/models/restful-model-collection.js
- src/models/restful-model.js
- yarn.lock
[Lodash](https://lodash.com/) is a modern version of [Underscore](https://underscorejs.org/) that is well-integrated into the bundling system. Most notably, it supports importing only the parts of the library that you need, so you don't need to pull in the parts that are unused.
This pull request drops Underscore and replaces it with Lodash.
> Replace underscore with lodash

- package.json
Guys we are using this package and it's huge 100+Mb unpacked in node_modules, 
It's because it contains enormous amount of garbage like examples, and even log from developer machine, unpack and see https://registry.yarnpkg.com/nylas/-/nylas-4.2.2.tgz
This PR fixes this situation making your library small and beautiful.
Please merge and publish new version, as current highly increase build times and our app size.
> Fix package size

- example/authentication/routes/index.js
Was getting `400: "Error expanding 'fields' parameter. Cannot find matching fields for path 'email'"` responses from google, because the fields param no longer works; dropping it. 
See: https://meta.stackoverflow.com/questions/376116/cannot-sign-in-with-google-error-expanding-fields-parameter-cannot-find-matc
> rm deprecated field in google auth

- __tests__/management-account-spec.js
These tests have been problematic for a while. Fixes include:
- Added better mocking on `Nylas.accounts.connection.request` to account for multiple requests with different return values.
- Removing `catch` statements
- Adding `done()` callbacks and `expect.assertions(3)`
- Fixing endpoints
> better mocking in management-account-spec

- src/nylas-connection.js
- src/nylas.js
Fixing the error "Cannot create property 'statusCode' on string" when we 
set the `server_error` and we get a `statusCode`.
Fixes #81
> fix: Append server_error to error.message and not reassign variable

- __tests__/account-spec.js
- __tests__/management-account-spec.js
- src/models/account.js
note: billing_state doesn't exist yet on GET [/account](https://docs.nylas.com/reference#account), so only asserting on GET [.../accounts](https://docs.nylas.com/reference#aclient_idaccounts)
> add billing_state to Account obj

- .travis.yml
Versions 11 & 12 are currently supported, so we should run travis builds on them.
> run travis builds for Node 11 & 12

- CHANGELOG.md
- __tests__/management-account-spec.js
- src/models/management-account.js
The account management [GET /accounts](https://docs.nylas.com/reference#aclient_idaccounts) endpoint returns an `email` attribute on the account object, which we should persist on the `ManagementAccount` object. 
I named this attribute `emailAddress` for consistency with the `Account` object.
> Support 'email' and 'provider' on ManagementAccount

- README.md
- example/sample-app/app.js
- src/models/attributes.js
- src/models/delta.js
- src/models/management-account.js
- src/models/management-model-collection.js
- src/models/management-model.js
- src/nylas-connection.js
- src/nylas.js
Migrates to `client_id` and `client_secret` naming. Adds a deprecation warning.
> migrate to client_id and client_secret naming 

- example/sample-app/package.json
The example app fails to start up. There's an error about the appId and secret being missing, even though I set the client ID, client secret, and session secret. Bumping the version to `^4.7.0` fixes that error. I don't know if any other code needs to be changed; I can't see from Releases what the breaking changes were between version 2 to 3 and 3 to 4.
> sample-app: bump nylas dependency version

- CHANGELOG.md
- src/nylas.js
Old: `(node:47191) [DeprecationWarning] Warning: "appId" will be deprecated in version 5.0.0. Use "clientId" instead.`
New: `(node:49330) [Nylas] DeprecationWarning: "appId" will be deprecated in version 5.0.0. Use "clientId" instead.`
> Update DeprecationWarning format

- CHANGELOG.md
- __tests__/connect-spec.js
- src/models/connect.js
- src/nylas-connection.js
- src/nylas.js
I initially was going to have a test that tested compatibility with every provider, which is why there are so many email credential variables. But then didn't really see the benefit of it - what are your thoughts?
Also, while implementing this, I didn't see the point of the if statement you put in the Connect class constructor. Since the connection is instantiated in `nylas.js` from NylasConnection, won't the connection always be an instance of NylasConnection?
> implement /connect/authorize

- example/webhooks/index.js
Hi all! I recently tried implementing this example and ran into a couple of issues, so thought I would submit a PR with what worked for me :)
The main issue I ran into is that the rawBody parsing middleware processes asynchronous streaming data, but calls `next` immediately. This leads to a race condition where the rawBody may not be fully parsed before the webhook consumer logic is called. I added an event handler for `end` to call the `next` callback so that the function is fully asynchronous and rawBody will be complete before moving on to the next middleware. I also added some error handling for good measure, though this wasn't strictly needed.
A second issue, once I had that resolved, is that the `bodyParser.json` parsing library relies on streaming the same request that we processed …
> makes webhook parsing middleware fully async, adds error handling

- __tests__/management-account-spec.js
- __tests__/nylas-api-spec.js
- __tests__/restful-model-collection-spec.js
- __tests__/webhook-spec.js
I was getting tired of seeing the deprecation warnings when running the tests so I figured I'd just get this out 😅
> update tests with client id and client secret naming

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/attributes.js
- src/models/event.js
This is to address issue #146 
I'm unsure how we should deal with the Event attributes b/c it seems as though only one attribute type can be associated to a param. Also, I don't think we can support updating and creating events using the `when` param as well as the `start` and `end` params b/c then we wouldn't know which param to use to create/update the event. Open to suggestions or ideas that I might've overlooked though!
> support time, date, start_date, and end_date for creating and updating events

- package-lock.json
- src/models/connect.js
Currently, the `/connect/authorize` and `/connect/token` don't really throw an error.
The error is resolved, but this is not very practical at all, because we end up having a code like that when using the endpoints in order to catch errors :
```js
return Nylas.connect.authorize(options)
.then(res => {
if (res instanceof Error) handleError(res);
return Nylas.connect.token(res.code);
})
.then(res => {
if (res instanceof Error) handleError(res);
return res;
});
```
Where we would normally just do :
```js
return Nylas.connect.authorize(options)
.then(res => Nylas.connect.token(res.code))
.catch(e => handleError(e));
```
- `Fix` Removed useless then an catch in `/connect/authorize` and `/connect/token`
I confirm that this contribution is made under the terms of the MIT license and that I have …
> Fix: Throwing on connect error

- CHANGELOG.md
- __tests__/thread-spec.js
- src/models/thread.js
Updating the Thread model to use EmailParticipant instead of Contact for the participants attribute. This is consistent with the Message model.
Re: https://github.com/nylas/nylas-nodejs/issues/162
> Update thread participants to use EmailParticipant

- CHANGELOG.md
- __tests__/file-spec.js
- src/models/file.js
Adding `knownLength` to the formData allows us to accept streaming uploads from S3.
Re: https://github.com/request/request/issues/2800#issuecomment-427378925
>  form-data (https://github.com/form-data/form-data) automatically detects the size it needs to send when using fs.createReadStream. That does not work for streams from s3, thus you need to supply it yourself
> add knownLength to file upload

- CHANGELOG.md
- __tests__/thread-spec.js
- src/models/thread.js
Fixing a bug reported here: https://github.com/nylas/nylas-nodejs/pull/130
- Renaming the `thread.folder` attribute to `thread.folders`, consistent with the API response (a list of folders) and the edge case that different messages in a single thread can be in different folders.
- Emitting deprecation warnings when the the old `.folder` attribute is used, but still supporting it.
- Using `attributes.collection` instead of `attributes.object` for the thread folders, as it is an array of folders, not just a single folder object.
> update thread.folders to use Folder itemClass

- CHANGELOG.md
- src/models/attributes.js
- src/models/restful-model.js
Pulling bugfixes out of the typescript migration PR https://github.com/nylas/nylas-nodejs/pull/130
The get method is used to get a contact's picture, but was previously not using the callback.
> bugfix for get contact picture

- CHANGELOG.md
- src/nylas-connection.js
Re: https://github.com/nylas/nylas-nodejs/issues/172 users reporting bug where application crashes due to an undefined response. 
Taking this as a another reason to prioritize moving off of request, re: https://github.com/nylas/nylas-nodejs/issues/174
> check for undefined response and reject

- CHANGELOG.md
- __tests__/nylas-api-spec.js
- src/nylas.js
Re: https://github.com/nylas/nylas-nodejs/issues/176 we should be explicitly rejecting in `exchangeCodeForToken` if we don't receive a token in the response.
> exchangeCodeForToken should reject when no access_token returned

- CHANGELOG.md
- __tests__/contact-restful-model-collection-spec.js
- __tests__/contact-spec.js
- src/models/contact-restful-model-collection.ts
- src/models/contact.ts
- src/models/draft.ts
- src/nylas-connection.ts
Implementing support for [GET /contacts/groups](https://docs.nylas.com/reference#contactsgroups)
- Renamed `Groups` to `Group` (where `Groups` is an array of `Group` objects)
- Changed exports from contact.ts to also export `Group`
- Added `ContactRestfulModelCollection`
> Contact groups

- CHANGELOG.md
- __tests__/calendar-restful-model-collection-spec.js
- __tests__/calendar-spec.js
- src/models/calendar.ts
- src/models/restful-model-collection.ts
- Supporting POST & PUT for calendars. 
- Adds isPrimary, location and timezone attributes.
- Expand test coverage
- Supporting DELETE for calendars
- Refactor delete message to return JSON response (previous delete responses were empty, so this was not needed)
- Expand test coverage
Will address job statuses in a follow-up PR
> Calendar CRUD

- package-lock.json
- package.json
- src/models/delta.ts
- src/models/message.ts
- src/models/restful-model-collection.ts
- src/models/restful-model.ts
- src/nylas-connection.ts
Lodash is quite big package and often used for things supported
natively.
This diff will allow to cut some bytes from node_modules.
https://packagephobia.com/result?p=nylas
> Replace lodash with native tools

- CHANGELOG.md
- __tests__/draft-spec.js
- __tests__/restful-model-collection-spec.js
- src/models/calendar.ts
- src/models/draft.ts
- src/models/restful-model-collection.ts
We should consistently be passing callback as the last argument to public functions. Added tests for backwards compatibility, so users can still use the old parameter ordering if they want to.
> Be consistent about callback parameters

- example/sample-app/package.json
- package-lock.json
- package.json
- src/models/restful-model-collection.ts
Async package is quite big (especially v2 with lodash in dependencies).
In this diff I replaced it with simple promise flow.
https://packagephobia.com/result?p=async
> Drop async

- src/config.ts
- src/nylas-connection.ts
- src/nylas.ts
"require" was used in nylas connection to get options from static
class properties.
In this diff I moved the source of data to separate module which can be
imported by any module and refactored static properties with getters and
setters to preserve existing behaviour.
This is necessary simplification before replacing "request" with `node-fetch`.
> Avoid commonjs and circular dependencies

- src/nylas-connection.ts
Fixing a user-reported issue where `nylas.drafts.build({})` was returning the `RestfulModel` type, not the `Draft` type
> typing fixes

- __tests__/delta-spec.js
- __tests__/file-spec.js
- src/models/file.ts
- src/models/restful-model-collection.ts
- src/nylas-connection.ts
- src/nylas.ts
Currently types are specified as weak type `{[string]: any }`. Such type
make it quite hard to replace deprecated "request" with something else
(I'm planning to use node-fetch).  In this diff I specified all fields
explicitly and made `path` a mandatory field.
> Make connection.request types more strict

- __tests__/nylas-api-spec.js
- package-lock.json
- package.json
- src/nylas.ts
Ref https://github.com/nylas/nylas-nodejs/issues/174
Migrating whole library from "request" at once would be quite massive.
In this diff I migrated only exchangeCodeForToken to figure out how to
test and install dependencies.
> Migrate exchangeCodeForToken to node-fetch

- __tests__/delta-spec.js
- package-lock.json
- package.json
- src/models/delta.ts
- src/nylas-connection.ts
Ref https://github.com/nylas/nylas-nodejs/issues/174 https://github.com/nylas/nylas-nodejs/pull/214
Another migration example with node streams. Also added abort-controller polyfill and getRequest analog of requestOptions method in nylas connection
> Migrate delta streaming to node-fetch

- src/models/event.ts
The Nylas Calendar API has a new beta feature of adding a new [metadata field to calendar events](https://www.nylas.com/blog/event-metadata). This PR makes the feature available via the Nylas Node.js SDK. 
> [58040] Added support for event metadata

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/event.ts
- src/nylas-connection.ts
#227 added support for event metadata, this PR enhances this feature and allows for a user to query metadata using either the `metadata_key`, or `metadata_value`, or `metadata_pair` parameters.
Adding a metadata object is simple. Add the object under the `metadata` key when creating an event:
```
const event = nylas.events.build({
title: 'New Years Party!',
calendarId: CALENDAR_ID,
when: { start_time: 1546290000, end_time: 1546300800 },
participants: [{ email: 'swag@nylas.com', name: 'My Nylas Friend' }],
location: 'My House!',
metadata: {
'event_type': 'gathering'
}
});
```
To query events based on metadata, you can filter on three different parameters:
- `metadata_key` (string or array) to filter based on the keys within the metadata object
- `metadata_value` (string or array) to filter …
> [59911] Add support for querying event metadata

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v5.4.0 release bringing in the following new features:
* Add `metadata` field in the Event model to support new Event metadata feature (#227)
* Add support for filtering `metadata` using `metadata_key`, `metadata_value`, and `metadata_pair` (#228)
* Updated dependencies `lodash`, `y18n`, and `pug` to the latest stable version (#222)
> [59707] 5.4.0 Release

- CHANGELOG.md
- __tests__/calendar-restful-model-collection-spec.js
- __tests__/contact-restful-model-collection-spec.js
- __tests__/job-status-spec.js
- __tests__/nylas-api-spec.js
- __tests__/nylas-connection-spec.js
- __tests__/resource-spec.js
- src/nylas-connection.ts
The `requests` library has been deprecated for a while now. We've since moved on to `node-fetch` as it's supported elsewhere in the SDK. Test suite has been updated as well to make sure that we don't fail because of this change.
Please see #233 for reviewer comments.
> [59706] Replace deprecated 'request' library (Rebased)

- package-lock.json
- package.json
- src/models/delta.ts
- src/nylas-connection.ts
This is a follow up to #234 that I forgot to add to the PR. First commit is to address the redundant `getRequest` method. Second commit is to fix form-data which required a different approach given that we switched from `request`.
> node-fetch minor fix and cleanup

- CHANGELOG.md
- src/models/NylasApiError.ts
- src/nylas-connection.ts
Previously, we would only return generally the error message. Now we return a custom error object (that extends `Error`) that properly stores all of the error values we get back from the API and sets them in a way that is more native than just returning a string.
The new `NylasApiError` class extends the `Error` class and both sets the build-in properties of Error and extends the error class to provide more values if needed. The following properties are made availalbe by the class:
- `name` (string): The name of the error, derived from the [API Errors page](https://developer.nylas.com/docs/developer-tools/api/errors/) (e.g. `Bad Request`)
- `message` (string): The error message returned from the API (e.g. `No recipients specified`)
- `statusCode` (number): The status code returned from …
> [60372] Return better error details from API

- CHANGELOG.md
- src/models/calendar-restful-model-collection.ts
- src/models/contact-restful-model-collection.ts
- src/models/restful-model-instance.ts
- src/nylas-connection.ts
Some classes were returning a generic type, rendering some calls and functionality useless. This PR aims at fixing this by properly setting the type of objects that that extend `RestfulModelCollection` or `RestfulModelInstance` to provide the user access to type-specific properties and methods.
> [61828] Fix typing for classes that extend `RestfulModelCollection` or `RestfulModelInstance`

- CHANGELOG.md
- __tests__/draft-spec.js
- src/models/draft.ts
The Node SDK only added a tracking object to the payload if the draft was never "created" before (created in the Nylas API, as in the object was not `.save()` yet and does not have a draft ID), which is allowed according to the [Message Tracking documentation](https://developer.nylas.com/docs/developer-tools/webhooks/message-tracking/#enabling-tracking). However if the user has already created a `draft` object in the Nylas and tries to send it with a tracking object, it never gets added. This PR allows for a tracking object to be included in either case. 
> [62051] Draft tracking object not being added to a pre-existing `draft` object

- CHANGELOG.md
- __tests__/file-spec.js
- src/models/file.ts
- src/nylas-connection.ts
When downloading a file, the body returns `undefined`. This was due to a previous change when we cut over from the old `requests` library and moved to the `node-fetch` library. Test suite has also been updated to ensure that we have coverage for this in the future.
> [62896] `undefined` returned when trying to download file

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v5.5.0 release bringing in the following fixes:
* Fix tracking object not being added to a pre-existing `draft` object (#241)
* Removed `request` dependency and related import statements (#240) 
* Fix `undefined` response when downloading file (#242)
> v5.5.1 Release

- src/nylas-connection.ts
Version 5.5 has a breaking change where it calls `JSON.stringify` on `options.body` regardless of `options.json`. This breaks the [send raw mime](https://developer.nylas.com/docs/developer-tools/sdk/javascript-sdk/#send-raw-mime) functionality. I document this in a bit more detail here: https://github.com/nylas/nylas-nodejs/issues/246
Checking to see if options.json is explicitly set to `false` seems pretty safe here (rather than make the condition `options.body && options.json` as that breaks some calendar unit tests even though it's probably a bit more semantically correct). It looks like this library use to do something similar: https://github.com/nylas/nylas-nodejs/commit/b995b4f4489c09e05f07c810772b7d816399fe4e#diff-2de4f9bb82a400d2734c75d30d64883eec745110373fcde2c3e46fea7d3eb325L229 …
> Respect options.json a bit more to fix sending raw mime (fixes #246).

- CHANGELOG.md
- __tests__/account-spec.js
- __tests__/calendar-restful-model-collection-spec.js
- __tests__/calendar-spec.js
- __tests__/contact-restful-model-collection-spec.js
- __tests__/contact-spec.js
- __tests__/delta-spec.js
- __tests__/draft-spec.js
- __tests__/event-spec.js
- __tests__/file-spec.js
- __tests__/job-status-spec.js
- __tests__/label-spec.js
- __tests__/message-spec.js
- __tests__/nylas-api-spec.js
- __tests__/resource-spec.js
- __tests__/thread-spec.js
- __tests__/webhook-spec.js
- src/models/event.ts
- src/models/file.ts
- src/nylas-connection.ts
Lots of tests were returning a pass before being properly evaluated as a result of the Jest test cases being written without it properly being told to wait for the async calls to resolve before evaluating. This PR also found a few minor issues that were fixed:
* `Event.rsvp()` `callback` parameter should be optional.
* Uploading a `File` should expect a JSON as the API returns metadata
* Converting raw MIME emails to JSON before we can access fields
> [63072] Fixed Jest test cases not respecting async methods

- CHANGELOG.md
- __tests__/calendar-restful-model-collection-spec.js
- src/models/calendar-restful-model-collection.ts
This functionality was added by @gianpaj (#248), this PR just adds some consistency fixes to match Node SDK. This change enables support for the `/calendar/availability` endpoint.
```
const params = {
startTime: '1590454800',
endTime: '1590780800',
interval: 5,
duration: 30,
emails: ['jane@email.com'],
open_hours: [
{
emails: ['swag@nylas.com'],
days: ['0'],
timezone: 'America/Chicago',
start: '10:00',
end: '14:00',
object_type: 'open_hours',
},
],
};
const availability = await testContext.connection.calendars.availability(params);
```
> [63364] Add support for Calendar Availaiblity

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v5.6.0 release bringing in the following fixes:
* Fix Jest test cases not respecting async methods (#249)
* Fix issue with parsing raw MIME emails (#247)
* Add linting, enabled and set up eslint and prettier (#252)
* Add support for `/calendars/availability` endpoint (#248, #254)
* Add support for the Neural API (#253) 
> [63892] v5.6.0 Release

- CHANGELOG.md
- __tests__/neural-spec.js
- src/models/neural-categorizer.ts
- src/models/neural-signature-contact.ts
- src/models/neural.ts
This PR brings a few minor fixes for the SDK's implementation of Neural API. The main 3 fixes are:
* Support for multiple `message_id`s in one request to the Neural APIs that support it
* In `NeuralSignatureContact`, `phoneNumbers` was incorrectly cast as a String instead of array of Strings
* In `NeuralCategorizer`, we now support epoch for the `categorized_at` field
Updated code samples can be found below.
To use [Sentiment Analysis](https://developer.nylas.com/docs/intelligence/sentiment-analysis/):
```javascript
// To perform sentiment analysis on a message, pass in the message ID:
const messageAnalysis = await nylas.neural.sentimentAnalysisMessage([MESSAGE_ID]);
// To perform sentiment analysis on just text, pass in a string:
const textAnalysis = await …
```
> [64365] Apply fixes to the Neural API Implementation

- src/models/neural-signature-contact.ts
Very minor fix, two local class names were in plural form instead of singular form. 
> [65001] Change Links and Names to singular form

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/event.ts
The `Event` class was missing two fields that are present in recurring events, and are now added:
* `master_event_id` which represents the ID of the recurring event, and
* `original_start_time` which represents the start time of the recurring event
> [63848] Add missing fields for recurring events

- CHANGELOG.md
- src/nylas-connection.ts
Previously, if an error was encountered that wasn't caught (likely due to a server/network level error) it would not be rejected. We've added a catch block around the request to catch any error that didn't get caught before, and reject.
> [65520] Reject uncaught errors during requests

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/attributes.ts
- src/models/event-conferencing.ts
- src/models/event.ts
- src/models/neural.ts
This PR enables support for the new Nylas [Conference Sync (Beta)](https://developer.nylas.com/docs/connectivity/calendar/conference-sync-beta) feature.
`Event.conference` is now a field that will contain conference details for Events that contain them, and it can be populated when new events through the SDK.
You can read the values like so:
```javascript
const event = await nylas.events.find("id");
const conferencingProvider = event.conferencing.provider;
const conferenceURL = event.conferencing.details.url;
const conferencePassword = event.conferencing.details.password;
const conferenceMeetingCode = event.conferencing.details.meetingCode;
const conferencePhoneNumbers = event.conferencing.details.phone;
const conferencePin = event.conferencing.details.pin;
```
You can also build a new …
> [64663] Add Conferencing Support

- __tests__/event-spec.js
- src/models/event-conferencing.ts
- src/models/event.ts
The Event API, in addition to support for manually-added conference details, supports auto generating conference details. If you have an integration authorized and enabled for your Nylas account you can provide an `autocreate` object instead of a `details` object to have the Nylas API autofill the conferencing details.
To have Nylas autocreate the conference field for you, pass the `autocreate` object to the new event:
```javascript
const zoomEvent = nylas.events.build({
...
conferencing: {
provider: "Zoom Meeting",
autocreate: {
settings: {},
}
},
});
```
A few notes and things to keep in mind:
* Only **one** of `details` or `autocreate` can be present, and we have implemented client-side checking to enforce this rule
* Autocreating conferencing data is an asynchronous operation on the …
> [65378] Dynamic conferencing link creation support

- CHANGELOG.md
- src/models/restful-model.ts
The conditional logic in the RestfulModel `toJSON` method was not explicit enough on the value of `enforceReadOnly`, leading to JSON.stringify unintentionally ignoring read only values.
> [66948] Fix JSON.stringify omitting read only values

- __tests__/message-spec.js
- __tests__/neural-spec.js
- __tests__/nylas-connection-spec.js
- __tests__/restful-model-collection-spec.js
- src/models/attributes.ts
- src/models/calendar.ts
- src/models/contact-restful-model-collection.ts
- src/models/contact.ts
- src/models/delta-stream.ts
- src/models/draft.ts
- src/models/event-conferencing.ts
- src/models/event-participant.ts
- src/models/event.ts
- src/models/folder.ts
- src/models/management-model-collection.ts
- src/models/message.ts
- src/models/model-collection.ts
- src/models/model.ts
- src/models/neural-categorizer.ts
- src/models/neural-signature-contact.ts
- src/models/neural.ts
- src/models/restful-model-collection.ts
- src/models/restful-model-instance.ts
- src/models/restful-model.ts
- src/models/thread.ts
- src/models/webhook.ts
- src/nylas-connection.ts
As the SDK coverage grows, we need to decouple the standard functionality of a model from the specific functionality/structure of a "classic" Nylas API model. A "classic" Nylas API model is a model used for endpoints like `Event`, `Calendar`, `Message`, etc. where we expect the object to have an `id`, `account_id`, and `object` field. There are a lot of "dumb" models like `Contact.Emails` that would benefit from being cast as a basic model versus the current RestfulModel, as well as having the ability in the future for creating different types of models.
> [66695] Refactor Restfulmodel

- CHANGELOG.md
- example/webhooks/index.js
`JSON.parse(req.rawBody)` was throwing an error if `req.rawBody` was an empty string.
> [65926] Fix webhook example throwing error if body is not a raw body

- CHANGELOG.md
- src/models/event.ts
This PR addresses an issue that causes some PUT calls for Calendar objects to break. The issue was found when a customer was unable to update an event on API 2.2 with the API rejecting the call because `message_id` was present in the body. The messageId property is supposed to be readonly. We have 5 properties in Calendar that are now marked as readonly: `messageId`, `owner`, `iCalUID`, `status`, and `jobStatusId`.
> [64477] Fix readonly Calendar attributes

- CHANGELOG.md
- __tests__/calendar-restful-model-collection-spec.js
- src/models/calendar-restful-model-collection.ts
This PR enables support for the `/calendars/availability/consecutive` endpoint. 
To check for consecutive availability:
```javascript
const params = {
startTime: 1590454800,
endTime: 1590780800,
interval: 5,
duration: 30,
buffer: 30,
emails: [['jane@email.com'], ['swag@nylas.com']],
open_hours: [
{
emails: ['swag@nylas.com', 'jane@email.com'],
days: [0],
timezone: 'America/Chicago',
start: '10:00',
end: '14:00',
object_type: 'open_hours',
},
],
};
const consecutiveAvailability = await nylas.calendars.consecutiveAvailability(params);
```
> [66508] Add support consecutive availability

- CHANGELOG.md
- package-lock.json
- package.json
- src/nylas-connection.ts
New `nylas` v5.8.0 release bringing in the following new features:
* Add support for Calendar consecutive availability (#275)
* Enabled Nylas API 2.3 support
The new release also fixes the following:
* Fix issue where JSON.stringify would omit read-only values (#268, #266)
* Fix webhook example throwing error if body is not a raw body (#272)
* Fix readonly calendar attributes being sent for POST and PUT calls (#276)
> V5.8.0 Release

- CHANGELOG.md
- __tests__/scheduler-spec.js
- src/models/scheduler.ts
- src/nylas-connection.ts
This PR enables SDK support for the [Scheduler API](https://developer.nylas.com/docs/api/scheduler/#overview).
To create a new Scheduler page:
```javascript
const scheduler = nylas.scheduler.create({
access_tokens: ['test-access-tokens'],
config: {
timezone: 'America/Los_Angeles',
},
name: 'Test',
slug: 'test-slug',
});
```
To return all Scheduler pages:
```javascript
const schedulerList = await nylas.scheduler.list();
```
To return a single Scheduler page:
```javascript
const scheduler = await nylas.scheduler.find('SCHEDULER_ID');
```
To update a Scheduler page:
```javascript
const scheduler = await nylas.scheduler.find('SCHEDULER_ID');
scheduler.name = "Updated page name";
scheduler.save();
```
To delete a Scheduler page:
```javascript
await nylas.scheduler.delete('SCHEDULER_ID');
``` …
> [69572] Scheduler API Support

- CHANGELOG.md
- __tests__/component-spec.js
- src/models/component-restful-model-collection.ts
- src/models/component.ts
- src/nylas-connection.ts
This PR enables SDK support for the Nylas `/component` endpoints.
To create a new component:
```javascript
const component = nylas.component.create({
name: "New Component",
type: "agenda",
public_account_id: "{ACCOUNT_ID}",
access_token: "{ACCESS_TOKEN}",
});
```
To get all components:
```javascript
const componentList = await nylas.component.list();
```
To get a specific component:
```javascript
const component = await nylas.component.find("{COMPONENT_ID}");
```
To update a component:
```javascript
const component = await nylas.component.find("{COMPONENT_ID}");
component.allowedDomains = ["www.nylas.com"];
component.save();
```
To delete a component:
```javascript
await nylas.component.delete("{COMPONENT_ID}");
```
I confirm that this contribution is made under the terms of the MIT …
> [67847] Component CRUD Support

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/event-notification.ts
- src/models/event.ts
Add support for [Event notifications](https://developer.nylas.com/docs/connectivity/calendar/event-notifications).
To add notifications to an event:
```python
const notificationEvent = nylas.events.build({
...
notifications: [
{
body: 'Reminding you about our meeting.',
minutes_before_event: 600,
subject: 'Test Event Notification',
type: 'email',
},
{
type: 'webhook',
minutes_before_event: 600,
url: 'https://hooks.service.com/services/T01A03EEXDE/B01TBNH532R/HubIZu1zog4oYdFqQ8VUcuiW',
payload: JSON.stringify({
text: 'Your reminder goes here!',
}),
},
{
type: 'sms',
minutes_before_event: 60,
message: 'Test Event Notification',
},
],
});
```
To retrieve event notification details of an event:
```python
const event = await nylas.events.find("id");
const minutesBeforeEvent = …
```
> [72428] Support Event notifications

- CHANGELOG.md
- __tests__/calendar-spec.js
- __tests__/management-account-spec.js
- src/models/calendar.ts
- src/models/management-account.ts
The metadata feature first introduced for events has expended to `Calendar` and `Account`. This PR adds support for this change. More information on the expansion of the metadata can be found here: https://developer.nylas.com/docs/developer-tools/api/metadata
```javascript
const calendar = nylas.calendars.create();
calendar.name = "My New Calendar";
calendar.description = "Description of my new calendar";
calendar.location = "Location description";
calendar.timezone = "America/Los_Angeles";
calendar.metadata = {
test: "true",
};
calendar.save();
// Or you can update a calendar with metadata
const calendar = nylas.calendars.first();
calendar.metadata = {
test: "true",
};
calendar.save();
```
```javascript
const calendar = nylas.calendars.list({metadata_key: "test"});
```
```javascript …
```
> [73526] Metadata support for Calendar and Accounts

- CHANGELOG.md
- __tests__/message-spec.js
- src/models/message.ts
The Nylas API now supports metadata for existing messages. This is a followup to #286. 
```javascript
const message = Nylas.messages.first();
message.metadata = {
test: "true",
};
message.save();
```
```javascript
const messages = Nylas.messages.list({metadata_key: "test"});
```
> Metadata support for Messages

- CHANGELOG.md
- __tests__/scheduler-restful-model-collection-spec.js
- src/models/scheduler-booking-request.ts
The Scheduler booking timeslot endpoint requires the booking request payload to include a value for `additional_emails` and `additional_values` even if they are set to empty or null. This PR sets them to a blank array/object to avoid this error.
> Scheduler booking timeslot hotfix

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v5.10.1 patch release fixes the following issue:
* Fix bug where booking a valid timeslot resulted in an API error (#290)
> v5.10.1 Release

- CHANGELOG.md
- src/models/attributes.ts
- src/models/event-participant.ts
- src/models/event.ts
- src/models/restful-model.ts
A recent API update caused updating an event using the SDK to return an error because the SDK sends a Participant's status as well as an object key within the Event.when object. 
> [74829] Fix bug where updating an Event results in an API error

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v5.10.2 patch release fixes the following issues:
* Fix Scheduler and Component types (#293)
* Fix Component sending unmodifiable fields during update (#293)
* Fix bug where updating an event resulted in an API error (#292)
> v5.10.2 Release

- CHANGELOG.md
- __tests__/job-status-spec.js
- src/models/calendar.ts
- src/models/contact.ts
- src/models/folder.ts
- src/models/job-status.ts
- src/models/message.ts
This PR improves the Job Status support on this SDK. Some models are missing a `job_status_id` key, as well as the Job Status model itself was missing an `original_data` key. A new helper method was also introduced to the `JobStatus` object called `isSuccessful()` that returns a boolean value representing a successful job status.
> [75824] Job Status improvements

- CHANGELOG.md
- __tests__/nylas-api-spec.js
- src/nylas.ts
The `oauth/authorize` endpoint supports a `provider` option for forcing authentication against a different provider, this PR adds it in.
> [76422] Add missing `provider` option for `urlForAuthentication`

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v5.10.3 patch release provides the following enhancements:
* Add missing `provider` option for `urlForAuthentication` (#296)
* Job status improvements (#295)
> v5.10.3 Release

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/event.ts
Some recurring events throw an error from the API when sending an empty list of notifications. This could occur without the user setting an empty list of notifications as the Node SDK defaults all array-type attributes to an empty array even if not directly set the attribute. This PR overrides this functionality and prevents `notifications` from being set if the user did not explicitly set the attribute.
> [77455] Prevent `Event` from sending empty notification array when notifications were not set

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v5.10.4 patch release provides the following fix:
* Prevent `Event` objects from sending an empty list of notifications when not set, causing errors for recurring events (#298)
> v5.10.4 Release

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/event-participant.ts
This PR enables two new fields in `EventParticipant`, `comment` and `phoneNumber`. More detail can be found in the [API reference](https://developer.nylas.com/docs/api/#post/events).
> [78166] Add `comment` and `phoneNumber` fields to `EventParticipant`

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/event.ts
- src/models/model.ts
- src/models/restful-model.ts
- src/models/when.ts
`saveRequestBody()` was introduced prior to the v6.0 release to enforce read-only attributes not being serialized for outgoing API calls. With the introduction of the `Model` superclass in v6.0 a lot of objects got refactored from extending `RestfulModel` to `Model`, but `saveRequestBody()` remained on `RestfulModel`. This broke the serialization of `Model` properties. To resolve this, we moved `saveRequestBody()` to the `Model` superclass.
> [78923] Fix `saveRequestBody()` for `Model` class

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/event.ts
- src/models/when.ts
This PR enables support for [generating an ICS file from an Event](https://developer.nylas.com/docs/api/#post/events/to-ics).
```javascript
const exampleEvent = await nylas.events.find('{id}');
// Generate an ICS from an event
let ics = await exampleEvent.generateICS();
// You can also pass ICS Options for more configuration
ics = await exampleEvent.generateICS({
iCalUID="test_uuid",
method="add",
prodId="test_prodid"
})
```
> [76803] Event to ICS Support

- CHANGELOG.md
- package-lock.json
- package.json
- src/models/free-busy.ts
New `nylas` v6.1.0 minor release provides the following new features:
* Add support for `Event` to ICS (#308)
* Add `comment` and `phoneNumber` fields to `EventParticipant` (#305)
* Add support for `calendar` field in free-busy, availability, and consecutive availability queries (#306)
and the following fix:
* Fix issue where properties of `Model` type were sending read-only attributes to the API (#309) 
> v6.1.0 Release

- CHANGELOG.md
- __tests__/delta-spec.js
- src/models/delta-collection.ts
- src/models/delta-stream.ts
- src/models/delta.ts
- src/models/deltas.ts
- src/nylas-connection.ts
This PR improves `Delta` support by adding a couple of new models and adding support for requesting a cursor (`/delta`) and long-polling (`/delta/longpoll`). The following changes have been made:
- `Delta` is now a RestfulModel representing a Delta object type
- `Deltas` is a new class representing the API object that contains a set of `Delta` objects
- `DeltaCollection` is a new class that contains all delta-related operations (including `latestCursor` and `startStream`)
- `NylasConnection.deltas` now returns a `DeltaCollection` object to maintain backwards compatibility as `latestCursor` and `startStream` have been moved out and `Delta` has become a model.
- `DeltaCollection.since(cursor: string)` returns the most recent set of deltas since the cursor passed in (GET `/delta`)
- …
> [76810] Improve `Delta` support

- CHANGELOG.md
- src/models/attributes.ts
- src/models/connect.ts
This PR fixes three issues in regards to Virtual Calendars:
1. Serializing a list of enums to JSON
2. The logic in determining a VirtualCalendar versus a NativeAuthentication
3. Unnecessary parameters during `Connect.authorize()` call leading to confusion
To expand on the third point, `Connect.authorize()` now takes 2-3 arguments compared to the previous 3-5:
1. name: string
2. emailAddress: string
3. clientId: string (optional, if not passed in it will just use the current clientId)
Compared to v6.0, `scope` and `settings` are no longer required as the API only accepts `['calendar']` for. scopes and an empty object for settings, so to prevent confusion we do not require these arguments and instead hardcode it in the class itself.
I confirm that this contribution is made under the terms …
> [80399] Fix Virtual Calendar logic and serialization

- CHANGELOG.md
- __tests__/draft-spec.js
- src/models/draft.ts
This PR adds support for adding a new field, `fileIdsToAttach: string[]`, in `Draft` which will allow users who want to attach files to a draft via file IDs. Due to the existence of `fileIds()` function in the `Message` superclass, we can't set this variable to a friendlier name without causing a breaking change.
Please note that this variable only adds files to a draft, to remove a file it must be done on the files array. Upon saving we will make sure to merge unique values in the outgoing payload.
```js
const draft = new Draft(nylas, {
to: [{ name: 'Nylas Swag', email: 'swag@nylas.com' }],
fileIdsToAttach = ["file_id_1", "file_id_2"],
}); …
```
> [79908] Add new field in `Draft` for adding files by file IDs

- CHANGELOG.md
- src/nylas-connection.ts
This PR enables support for Nylas API v2.5
> Enable Nylas API v2.5 support

- CHANGELOG.md
- src/models/scheduler.ts
This PR fixes the type `SchedulerBookingOpeningHoursProperties.days` to be a `string[]` and added in the following fields:
* `showWeekView` in `SchedulerAppearance`
* `additionalGuestsHidden` in `SchedulerBooking`
* `disableEmails` in `SchedulerConfig`
> [TSDK-247] Fix `SchedulerBookingOpeningHoursProperties.days` and add missing fields to Scheduler models

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v6.2.1 release provides the following changes and fixes:
* Fix circular dependency issue in `Attribute` (#324)
* Fix `SchedulerBookingOpeningHoursProperties.days` and add missing fields to Scheduler models (#330, #328)
* Enable Nylas API v2.5 support (#329)
* Bump `node-fetch` dependency from 2.6.1 to 2.6.7 (#322)
* Bump `ajv` sub-dependency from 6.10.2 to 6.12.6 (#325)
> v6.2.1 Release

- CHANGELOG.md
- src/nylas-connection.ts
Sometimes a call to the API might result in a 5xx server error with an HTML response. We should be accounting for this case and return a proper error instead of erroring out due to failed JSON parsing.
> Fix error when Nylas API returns non-JSON error

- CHANGELOG.md
- __tests__/management-account-spec.js
- src/models/management-account.ts
This PR adds support for new `authentication_method` field in `ManagementAccount`.
> [TSDK-262] Add new authentication method field to ManagementAccount

- CHANGELOG.md
- __tests__/message-spec.js
- src/models/message-restful-model-collection.ts
This PR enables support for directly getting a raw message from the API. Currently on the SDK you would need to get a message first then run `getRaw()` on it, which results in 2 API calls. This function exists on `MessageRestfulModelCollection` allowing you to get the message as raw directly using a message ID resulting in just one API call.
```ts
const messages = await nylas.messages.findRaw("message_id");
```
> Add support for getting raw messages directly from the API

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v6.2.2 release provides the following changes and fixes:
* Allow getting raw message by message ID directly instead of needing to fetch the message first
* Add new `authenticationType` field in `ManagementAccount`
* Fix JSON error thrown when Nylas API returns non-JSON error payload
> v6.2.2 Release

- Contributing.md
- src/config.ts
- src/nylas.ts
Support the ability to set the `redirect_on_error` url param so that when using hosted authentication  the user can be redirected back to the app on error. 
> Support Setting Redirect On Error in Authenticate URL Config

- CHANGELOG.md
- __tests__/job-status-spec.js
- __tests__/outbox-spec.js
- src/models/job-status-restful-model-collection.ts
- src/models/outbox-job-status.ts
- src/models/outbox.ts
- src/nylas-connection.ts
This PR improves Outbox job status for the Node SDK by allowing for fetching an `OutboxJobStatus` object by job status ID, as well as add in some missing fields from an Outbox job status object.
To get an outbox job status by ID, it's the same as you would get any Job Status, but in the background the SDK will identify if the job status is an outbox job status, and if so it will return the correct type:
```ts
const jobStatus = nylas.jobstatuses.find("outbox-job-status-id");
```
I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright …
> [TSDK-277] Improve Outbox job status support

- CHANGELOG.md
- __tests__/calendar-restful-model-collection-spec.js
- __tests__/calendar-spec.js
- __tests__/component-spec.js
- __tests__/contact-restful-model-collection-spec.js
- __tests__/contact-spec.js
- __tests__/draft-spec.js
- __tests__/event-spec.js
- __tests__/file-spec.js
- __tests__/folder-spec.js
- __tests__/job-status-spec.js
- __tests__/label-spec.js
- __tests__/message-spec.js
- __tests__/neural-spec.js
- __tests__/nylas-connection-spec.js
- __tests__/outbox-spec.js
- __tests__/resource-spec.js
- __tests__/scheduler-restful-model-collection-spec.js
- __tests__/scheduler-spec.js
- __tests__/thread-spec.js
- src/nylas-connection.ts
Sometimes the API won't respond with a JSON body, but given that the request completed without a status error, just return undefined.
> Catch a JSON error and return undefined

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v6.3.0 release provides the following changes and fixes:
* Add support for revoking a single access token (#337)
* Improve Outbox job status support (#341)
* Support Setting Redirect On Error in Authenticate URL Config (#338)
* Fix issue where an empty response body could trigger a JSON deserialization error (#340)
* Remove usage of unreliable `node-fetch response.size` (#339)
> v6.3.0 Release

- CHANGELOG.md
- __tests__/message-spec.js
- src/models/message-restful-model-collection.ts
This PR fixes a small bug where if someone passes in an array of one in findMultiple, it would throw an error because the API response is not an array.
> Fix issue where passing in an array of one for `MessageRestfulModelCollection.findMultiple` throws an error

- CHANGELOG.md
- src/models/calendar-availability.ts
- src/models/free-busy.ts
For calendar availability the response now includes `order` and for time slot there is an `emails` field as well. This PR adds both fields.
> Add missing order and emails field in calendar availability

- CHANGELOG.md
- package-lock.json
- package.json
New nylas v6.3.1 release provides the following changes and fixes:
* Add missing order and emails field in calendar availability (#344)
* Fix issue where passing in an array of one for `MessageRestfulModelCollection.findMultiple` throws an error (#343)
> v6.3.1 Release

- CHANGELOG.md
- src/models/draft.ts
This PR adds the missing `fileIdsToAttach` field into `DraftProperties` so that a user can pass that field in while initializing a new Draft.
> Add missing `fileIdsToAttach` field in `DraftProperties`

- __tests__/calendar-restful-model-collection-spec.js
- src/models/calendar-restful-model-collection.ts
I noticed the following error while attempting to use the "free busy" functionality:
Doing a manual CURL request with the same parameters was successful.
After some debugging I noticed that the code was attempting to `JSON.parse(json)`, where `json` was a JSON object and not a string. This resulted in the error I witnessed.
> [Bugfix] Fix bug in CalendarRestfulModelCollection

- CHANGELOG.md
- __tests__/calendar-restful-model-collection-spec.js
- __tests__/scheduler-restful-model-collection-spec.js
- src/models/calendar-restful-model-collection.ts
- src/models/model-collection.ts
- src/models/restful-model-collection.ts
- src/models/scheduler-restful-model-collection.ts
The scheduler endpoints were not using the correct base URL for API calls, resulting in errors for any scheduler operation. This PR ensures that the Scheduler endpoints use the correct url.
> Fix scheduler endpoint URL

- CHANGELOG.md
- package-lock.json
- package.json
New nylas v6.3.2 release provides the following changes and fixes:
* Add missing `fileIdsToAttach` field in `DraftProperties` (#347, #348)
* Fix JSON parse error when using `CalendarRestfulModelCollection.freeBusy` (#349)
* Fix base URL not being set for `SchedulerRestfulModelCollection` functions (#350)
> v6.3.2 Release

- CHANGELOG.md
- __tests__/draft-spec.js
- src/models/draft.ts
A followup to #348, this PR ensures that when setting `fileIdsToAttach` when initializing a `Draft` it actually sets it.
> Fix `fileIdsToAttach` field not being set when initializing a `Draft`

- CHANGELOG.md
- __tests__/event-spec.js
- package-lock.json
- package.json
New `nylas` v6.4.0 release provides the following addition and fix:
* Support collective and group events (#352)
* Fix `fileIdsToAttach` field not being set when initializing a `Draft` (#354)
> v6.4.0 Release

- example/webhooks/index.js
1. Fixed the incorrect tunnel index number.
```
node index.js
/Users/everton/projects/nylas-nodejs/example/webhooks/index.js:85
webhook_uri = JSON.parse(body).tunnels[1].public_url + '/webhook';
^
TypeError: Cannot read properties of undefined (reading 'public_url')
at Request._callback (/Users/everton/projects/nylas-nodejs/example/webhooks/index.js:85:46)
at self.callback (/Users/everton/projects/nylas-nodejs/example/webhooks/node_modules/request/request.js:185:22)
at Request.emit (node:events:527:28)
at Request.<anonymous> (/Users/everton/projects/nylasnodejs/example/webhooks/node_modules/request/request.js:1154:10)
at Request.emit (node:events:527:28)
at IncomingMessage.<anonymous> (/Users/everton/projects/nylas-nodejs/example/webhooks/node_modules/request/request.js:1076:12)
at …
```
> [Fix] Wrong body parse error - public_url undefined

- CHANGELOG.md
- __tests__/calendar-restful-model-collection-spec.js
- __tests__/calendar-spec.js
- __tests__/component-spec.js
- __tests__/contact-restful-model-collection-spec.js
- __tests__/contact-spec.js
- __tests__/draft-spec.js
- __tests__/event-spec.js
- __tests__/file-spec.js
- __tests__/folder-spec.js
- __tests__/job-status-spec.js
- __tests__/label-spec.js
- __tests__/message-spec.js
- __tests__/neural-spec.js
- __tests__/resource-spec.js
- __tests__/scheduler-restful-model-collection-spec.js
- __tests__/scheduler-spec.js
- __tests__/thread-spec.js
- src/nylas-connection.ts
Since the release of v6.3.0 we incorporated the use of `node-fetch`'s `.clone` function which allows us to clone the response body before exhausting the stream, in case we run into some sort of parsing error (usually with JSON parsing). This led to some issues with fetching in general, and after some research it seems to be a known issue on node-fetch < 3.0.0 where if `.clone` is used on a large response, it won't properly read the stream (https://github.com/node-fetch/node-fetch/issues/396, https://github.com/node-fetch/node-fetch/issues/151). 
This issue was fixed in v3 of node-fetch but we're not able to directly jump to that version as it has breaking changes. As a result, we've switched to removing the use of `clone` and instead we just get the buffer as a string and try to parse the …
> Remove use of `.clone` in `node-fetch` operations

- CHANGELOG.md
- package-lock.json
- package.json
New nylas v6.4.1 release provides the following fixes:
* Fixed issue where API response data was being lost (#358, #356)
* Fixed incorrect tunnel index number in webhook example (#357)
> v6.4.1 Release

- CHANGELOG.md
- __tests__/message-spec.js
- src/models/message.ts
The `Message` class was missing a `save()` function for updating an already existing message, so this PR adds it in.
```js
const message = await nylas.messages.first();
message.metadata = { "test": true };
message.save();
```
> Add Message.save() functionality for updating existing messages

- CHANGELOG.md
- package-lock.json
- package.json
New nylas v6.4.2 release provides the following changes:
* Add `Message.save()` functionality for updating existing messages (#362)
* Add missing `reminderMinutes` field in `Event` (#361)
> v6.4.2 Release

- CHANGELOG.md
- __tests__/calendar-restful-model-collection-spec.js
- __tests__/calendar-spec.js
- __tests__/component-spec.js
- __tests__/connect-spec.js
- __tests__/contact-restful-model-collection-spec.js
- __tests__/contact-spec.js
- __tests__/draft-spec.js
- __tests__/event-spec.js
- __tests__/file-spec.js
- __tests__/folder-spec.js
- __tests__/job-status-spec.js
- __tests__/label-spec.js
- __tests__/management-account-spec.js
- __tests__/message-spec.js
- __tests__/neural-spec.js
- __tests__/nylas-api-spec.js
- __tests__/outbox-spec.js
- __tests__/resource-spec.js
- __tests__/restful-model-collection-spec.js
- __tests__/scheduler-restful-model-collection-spec.js
- __tests__/scheduler-spec.js
- __tests__/thread-spec.js
- __tests__/webhook-spec.js
- src/nylas.ts
This PR converts the SDK's entry point, the `Nylas` class, from being static to non-static. The reason behind this change is to enable multiple configurations and more reuse of the `Nylas` object. Note that this also changes all the class's variables and functions to non-static.
The new way to init the Node SDK is like so:
```js
const nylasClient = new Nylas({clientId: 'clientId', clientSecret: 'clientSecret'});
const nylasConnection = nylasClient.with('access_token');
// Get all messages found in the user's inbox
nylasConnection.messages.list().then(messages => console.log(messages));
// Access to variables belonging to Nylas
const clientId = nylasClient.clientId;
const clientSecret = nylasClient.clientSecret;
const apiServer = nylasClient.apiServer;
const …
```
> Convert `Nylas` class from a static to a non-static class

- package-lock.json
- package.json
- src/config.ts
- src/models/webhook.ts
- src/services/tunnel.ts
- Create a new tunneling service that mimics the functionality of the CLI
- Intended use is to add `websocketEventListener` (or something like that) option to the upcoming server bindings feature, that automatically calls this
- Events should be output using the same mechanism as the automatic webhook registry
- Add the `message.bounce` webhook event (as it's in the CLI)
- Add region configs, carried over from the CLI
> [Isaac] v7 Tunneling Service

- src/services/tunnel.ts
Just noticed some things testing #366:
- `message.utf8Data.body` is doubly serialized so we need to deserialize twice. It's also in API-json format not `WebhookNotificationProperties`, so we need to convert it from JSON to WebhookDelta
- Replace console.log line with error
- Replace var with consst
- Added return types and jsdoc formatted comments
> Tunneling fixes

- src/services/tunnel.ts
Upon exiting somehow, we should clean up by deleting the created webhook. Couple of notes:
- Only invoke `deleteTunnelWebhook` on exit and point the other signals to `exit`, otherwise we override the default `SIGTERM`, etc. behavour: https://stackoverflow.com/a/14372355/1995715
- Can't listen on `SIGKILL`: https://nodejs.org/api/process.html#process_signal_events
> Delete tunnel webhook on exit

- package-lock.json
- package.json
For users who want to use our websocket webhook service, we need to have `webhooks` and `uuid` as a dependency or else it won't get pulled when they `npm install`
> Move websocket-related deps out of devDependencies

- CHANGELOG.md
- src/server-bindings/express-binding.ts
- src/server-bindings/server-binding.ts
This PR removes confusion as behind the scenes, `buildRoute` was taking either `routPrefix` or `/nylas` (if unset) and appending it to the paths. So if someone mounts the middleware at `/nylas`, the routes would have been `/nylas/nylas/...`. 
If we want to mount endpoints to /nylas:
```js
const express = require('express');
const { ServerBindings } = require('nylas/lib/config');
// The port the express app will run on
const port = 9000;
// The uri for the frontend
const clientUri = 'http://localhost:3000';
// Initialize an instance of the Nylas SDK using the client credentials
const nylasClient = new Nylas({
clientId: clientId,
clientSecret: clientSecret,
});
const app = express();
app.listen(port, () => console.log('App listening on port ' + port));
// Use …
```
> Remove `routePrefix` config from server bindings

- CHANGELOG.md
- src/server-bindings/express-binding.ts
- src/server-bindings/server-binding.ts
To ensure that the token exchange response is properly overridden, we need to use a callback instead of emitting an event as we can’t guarantee that the event gets emitted in-order before we return the response from the API. Especially if the user wants to implement any async code.
Now, when configuring your server binding, `exchangeMailboxTokenCallback` is a required field and takes a reference to a function that accepts two parameters; `accessToken: AccessToken, res: ServerResponse`. Currently, `ServerResponse` is just `Express.Response` but it will be expanded to include the response object of other frameworks. 
```js
const express = require('express');
const { Scope } = require('nylas/lib/models/connect');
const { ServerBindings } = …
```
> [v7.0.0] Implement callback instead of event emitter for mailbox token exchange

- CHANGELOG.md
- src/models/scheduler.ts
This PR fixes the json value mapped to `confermationEmailToHost` as "email" is actually plural. Adjusting the actual model variable name will be introduced in v7 as it's a breaking change.
> Fixed json value for `confirmationEmailToHost` in `SchedulerBooking`

- CHANGELOG.md
- __tests__/scheduler-spec.js
- src/models/scheduler.ts
This PR adds the `intervalMinutes` field in `ScheduleBooking`. Note that this field only takes a non-zero, positive integer that's divisible by 5. Else we have validation that runs when attempting to save that will throw an error.
> Add `interval_minutes` field in Scheduler booking config

- CHANGELOG.md
- src/models/event.ts
- src/models/scheduler.ts
This PR fixes issues relating to typing in:
- `Event`: `originalStartTime` should deserialize to `Date`, so replace `number` type to `Date`.
- `SchedulerBookingOpenHours`: The `account_id` filed from the API was being deseralized to `dropdownOptions` instead of `accountId`.
> Fix typing issues in event and scheduler open hours

- CHANGELOG.md
- __tests__/job-status-spec.js
- src/models/job-status.ts
This PR adds a new `metadata` field to the `JobStatus` class.
> Add `metadata` field to `JobStatus`

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v6.5.0 release provides the following changes:
* Add `metadata` field to `JobStatus` (#379)
* Add `interval_minutes` field in Scheduler booking config (#378)
* Fixed `Event.originalStartTime` type to be `Date` (#381, #380) 
* Fixed `SchedulerBookingOpeningHours.accountId` deserialization (#381)
* Fixed json value for `confirmationEmailToHost` in `SchedulerBooking` (#377)
> v6.5.0 Release

- CHANGELOG.md
- src/config.ts
- src/nylas.ts
- src/server-bindings/express-binding.ts
- src/server-bindings/server-binding.ts
- src/services/routes.ts
This PR's main change is pulling out the underlying logic of the routes used in the middleware created for Express and moving it to `Routes`. This new module's purpose is to allow implementing clients that don't use one of the supported frameworks served by `ServerBindings` still an easy way to integrate Nylas into their code and pair it with our frontend SDKs we provide (@nylas/nylas-js, @nylas/nylas-react).
This code also brings forward a breaking change, the `Nylas.exchangeCodeForToken` now expects the optional callback parameter to anticipate a `AccessToken` object instead of a string for the `accessToken` parameter. 
We're going to use `fastify` as we currently do not support this framework to demonstrate how using `Routes` can make  it easy to implement these routes:
```js
const …
```
> Abstracting middleware logic

- CHANGELOG.md
- __tests__/event-spec.js
- src/models/event-participant.ts
- src/models/event.ts
This PR ensures that on a create the event's participant status is sent.
> Fix issue with `EventParticipant` not sending status on new event creation

- CHANGELOG.md
- src/models/scheduler.ts
"Emails" should be pluralized to align with the API.
> Rename `confirmationEmailToHost` to `confirmationEmailsToHost` in `SchedulerBooking`

- CHANGELOG.md
- src/models/event.ts
Add the following fields to `Event`:
* customeEventId: string
* oragnizerEmail: string (read only)
* organizerName: string (read only)
* visibility: string (read only)
> Add additional Event fields

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v6.5.1 release provides the following changes:
* Add additional `Event` fields (#387)
* Fix issue with `EventParticipant` not sending status on new event creation (#386)
> v6.5.1 Release

- CHANGELOG.md
- src/services/tunnel.ts
This PR adds error handling when deleting a webhook. Sometimes if a webhook is terminated via the dashboard or API before the SDK handles it, the SDK throws an error when attempting to delete the webhook. Now, it will warn the user but it won't cause a fatal error anymore.
> Gracefully handle error on webhook deletion

- __tests__/event-spec.js
- src/models/event-reminder-method.ts
- src/models/event.ts
Adding Event Reminder method to the Event object. Just creating a PR to see if I am on the right track here. I can see that our Object Schema from our API and the response we get back differ. There is some duplication that needed to be done to get this working. However, in this.validate() I am adding some validations to make sure the request passes through.
Questions And Concerns
So I am making sure no reminders are set on PUT calls using the id field
I still need to add some tests to test out read and write for this property
Also when you get the response back we get a reminders object :( So Mapping is different, so I had to duplicate some value with how our fromJson and toJson behave. But the weird thing is reminder_minutes is a string in the post request but it is an integer in the …
> TSDK-417 Adding Event Reminders to Event Object

- CHANGELOG.md
- __tests__/calendar-spec.js
- src/models/calendar.ts
This PR adds support for the new colors field in the Calendar model. Please note that this field is read only, and for Microsoft calendars only.
> Add support for calendar colors

- CHANGELOG.md
- __tests__/webhook-notification-spec.js
- src/models/webhook-notification.ts
This PR adds additional fields for the webhook notification class. There's also a new model, `WebhookObjectExtras` for extra fields that can appear for job status notifications.
> Add additional fields for job status webhook notifications

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v6.6.0 release provides the following changes:
* Add additional fields for job status webhook notifications (#398)
* Add support for calendar colors (for Microsoft calendars) (#397)
* Add support for event reminders (#399)
* Fix typo in `SchedulerBooking.calendarInviteToGuests` attribute (#393)
* Bump `minimist` sub-dependency from 1.2.5 to 1.2.6 (#389)
> v6.6.0 Release

- CHANGELOG.md
- __tests__/calendar-spec.js
- src/models/calendar.ts
In #397 the implementation in the SDK was based off of an earlier implementation from the API, this PR adjusts the field name and type to reflect what's provided in the Nylas API.
> Fix calendar color implementation

- CHANGELOG.md
- package-lock.json
- package.json
New `nylas` v6.6.1 release brings the following:
* Fix calendar color implementation (#402)
> v6.6.1 Release

- CHANGELOG.md
- __tests__/nylas-connection-spec.js
- src/models/rate-limit-error.ts
- src/nylas-connection.ts
This PR adds support for rate limit 429 headers from the API.
> Add Rate Limit error support

- CHANGELOG.md
- src/models/event.ts
Changed the Event `visibility` field from being read-only to writable to have parity with the recent API changes.
> Changed Event `visibility` field to be writeable

- __tests__/nylas-api-spec.js
- src/config.ts
- src/nylas.ts
Our Hosted Authentication method doesn't give the ability to change the response_type query parameter. Added the functionality to do that. It will either be `token` or `code`. If none provided it will default to the `code` as expected.
> Added responseType to AuthenticateUrlConfig

- CHANGELOG.md
- src/models/neural-categorizer.ts
- src/models/neural.ts
- src/models/outbox.ts
- src/models/scheduler-restful-model-collection.ts
- src/models/scheduler.ts
- src/nylas-connection.ts
This PR adds a default values for both the `Content-Type` and `Accept` headers for all outgoing connections to the Nylas API.
> [v7] Add defaults for Content-Type and Aceept headers for outgoing API requests

- CHANGELOG.md
- package.json
This PR adds an engine entry to the `package.json` targeting Node 14 and above. It's a best practice to outright define an engine entry in `package.json` and we've chosen the lowest currently supported Node version. Compatibility was verified using `ls-engine`. 
> Add Node engine entry to package.json

- CHANGELOG.md
- __tests__/webhook-notification-spec.js
- src/models/webhook-notification.ts
This PR adds two new fields and expands the type of the metadata in WebhookNotification for `Event` objects. The following changes occurred:
- Added `calendarId` to `WebhookObjectAttributes`
- Added `createdBeforeAccountConnection` to `WebhookObjectAttributes`
- Expanded metadata to support `Record<string, unknown>`, will deserialize to `MessageTrackingDataProperties` if it's a message or thread object as it did before.
> Add new attributes for Event webhook notifications

- CHANGELOG.md
- src/models/event.ts
This PR adds the `hideParticipant` field to `Event`.
> Add `hideParticipants` field to `Event`

- CHANGELOG.md
- package-lock.json
- package.json
New Nylas Node SDK v6.8.0 contains the following additions:
* Local webhook testing support (#422)
* Add `hideParticipants` field to `Event` (#420)
> v6.8.0 Release

- src/models/nylas-api-error.ts
We have occasionally seen API responses with an HTTP status of 409. That status is not mapped and causes an exception. This PR adds that mapping to correct that.
Additionally, [the API error documentation](https://developer.nylas.com/docs/api/errors) should also be updated to reflect the possibility of a 409 error.
> Add HTTP status 409 to error mapping

- src/models/when.ts
As specified in [Nylas Docs](https://developer.nylas.com/docs/api/#tag--Events--event-subobjects), the `When` object within a `Event` API support the following fields:
- `start_timezone`
- `end_timezone`
- `timezone`
This PR adds the related fields to the `When` object
> Add `startTimezone`, `endTimezone` and `timezone` fields to `When`

- CHANGELOG.md
- package-lock.json
- package.json
New Nylas Node SDK v6.9.0 contains the following additions:
* Add missing generic type in `RestfulModelCollection` for better type safety (#424)
* Add 409 to error mapping (#430)
* Add `startTimezone`, `endTimezone` and `timezone` fields to `When` (#429)
* Allow configurable timeout for API calls (#427)
* Bump `minimist` sub-dependency from 1.2.0 to 1.2.6 (#425)
* Bump `mkdirp` sub-dependency from 0.5.1 to 0.5.6 (#425)
To set the timeout you can add it as part of the initial Nylas SDK config:
```js
// Initialize an instance of the Nylas SDK using the client credentials and timeout
Nylas.config({
clientId: "CLIENT_ID",
clientSecret: "CLIENT_SECRET",
timeout: 60 // 60 second timeout
});
```
I confirm that this contribution is made under the terms of the MIT …
> v6.9.0 Release

- CHANGELOG.md
- __tests__/webhook-notification-spec.js
- src/models/webhook-notification.ts
This PR adds support for verifying the webhook signature of inbound webhook notifications.
```js
const express = require('express');
const cors = require('cors');
const app = express();
// Enable CORS
app.use(cors());
// The port the express app will run on
const port = 9000;
// Nylas app credentials
const NYLAS_CLIENT_SECRET = process.env.NYLAS_CLIENT_SECRET;
if (!NYLAS_CLIENT_SECRET) {
throw new Error('NYLAS_CLIENT_SECRET is required')
}
// Create a callback route for the Nylas Event Webhook
app.post('/', express.json(), async (req, res) => {
// Verify the Nylas Event Webhook signature to ensure the request is coming from Nylas
const signature =
req.headers['x-nylas-signature'] || req.headers['X-Nylas-Signature'];
if ( …
```
> Add support for verifying webhook signatures

- CHANGELOG.md
- package-lock.json
- package.json
New Nylas Node SDK v6.10.0 contains the following additions:
* Add support for verifying webhook signatures (#442)
> v6.10.0 Release

- src/apiClient.ts
- src/nylas.ts
- src/resources/webhooks.ts
- src/schema/webhooks.ts
This PR adds support for the Webhook schemas and models, enums for Webhook triggers, and all the Webhook API endpoints.
> Add Webhook support

- src/apiClient.ts
- src/index.js
- src/resources/auth.ts
- src/schema/auth.ts
- src/schema/error.ts
- src/schema/response.ts
Added token validation for issued access tokens & also ID tokens, both of them is successful return an OpenID for the corresponding user, also needed to extend error handling because of new struct of error on that endpoint
> Added token validation

- src/models/webhooks.ts
- src/resources/webhooks.ts
Creating a webhook should return a `WebhookWithSecret` response.
> Create a webhook should return secret

- .eslintrc.js
- .github/workflows/pull-reqeust.yml
- CHANGELOG.md
- jest.config.js
- package-lock.json
- package.json
- src/models/calendars.ts
- src/resources/auth.ts
- src/resources/redirectUris.ts
- tests/apiClient.spec.ts
- tests/auth.spec.ts
- tests/events.spec.ts
- tests/nylas.spec.ts
- tests/resources/applications.spec.ts
- tests/resources/auth.spec.ts
- tests/resources/calendars.spec.ts
- tests/resources/events.spec.ts
- tests/resources/grants.spec.ts
- tests/resources/redirectUris.spec.ts
- tests/resources/webhooks.spec.ts
- tests/testUtils.ts
- tsconfig.test.json
This PR fixes the current testing framework and adds many more. Our testing coverage is around 90% now.
We now also have 2 new fixes that have been identified by the tests:
* Fix path for destroying a redirect URI
* Fix model for updating an Event 
> Add Unit Tests for Node SDK v7 beta

- CHANGELOG.md
- src/models/auth.ts
- src/models/connectors.ts
- src/models/credentials.ts
- src/nylas.ts
- src/resources/connectors.ts
- src/resources/credentials.ts
- src/resources/grants.ts
- tests/resources/grants.spec.ts
Adds support for custom authentication, the connectors API and the credentials API.
> Add support for custom authentication, connectors, and credentials APIs

- src/models/folders.ts
- src/nylas.ts
- src/resources/folders.ts
- tests/nylas.spec.ts
- tests/resources/folders.spec.ts
- Added Node SDK Folders API
[JIRA](https://nylas.atlassian.net/browse/AV-2710)
[JIRA](https://nylas.atlassian.net/browse/AV-2711)
[JIRA](https://nylas.atlassian.net/browse/AV-2712)
> Added Node SDK Folders API

- CHANGELOG.md
- __tests__/calendar-restful-model-collection-spec.js
- src/models/attributes.ts
This PR closes #502. The parsing of number arrays was broken, setting the index instead of the value when desearializing. 
> Fix parsing of Number arrays

- CHANGELOG.md
- package-lock.json
- package.json
This PR bumps node fetch to close #496. 
> Bump `node-fetch` to `v2.6.12`

- __tests__/scheduler-spec.js
- src/models/attributes.ts
There was a bug that caused null values to return 0 for Attribute.Number. This will check if the value is null or not and return only if it's a valid Numbrer. This will avoid Number(null) returning 0.
> Fixing an issue with Attirbute.Number transforming null values into 0

- CHANGELOG.md
- src/nylas-connection.ts
Timeout now respects the value given. Closes #489.
> Fix configured timeout not being used

- __tests__/event-spec.js
- src/models/event.ts
Closes #470, fixes the issue "Bad Request: Visibility cannot have the value ''".
> Nullify visibility if visibility is an empty string

- __tests__/nylas-api-spec.js
- __tests__/nylas-connection-spec.js
- src/config.ts
- src/models/LoggingInterface.ts
- src/nylas-connection.ts
- src/nylas.ts
This PR adds in an option to pass in a logger instead of the SDK using `console` to log. Closes #456.
> Implement logger support

- CHANGELOG.md
- README.md
- __tests__/draft-spec.js
- package-lock.json
- package.json
* Add support for logging (#508, #456)
* Nullify replyToMessageId is an empty string (#484, #509)
* Nullify visibility if visibility is an empty string (#507, #470)
* Fix numbers defaulting to 0 instead of null (#469)
* Fix parsing of Number arrays (#503, #502)
* Fix configured timeout not being used (#506, #489)
* Bump `node-fetch` dependency from 2.6.1 to 2.6.12 (#504, #496)
> v6.11.0 Release

- src/apiClient.ts
- src/models/attachments.ts
- src/nylas.ts
- src/resources/attachments.ts
- src/resources/resource.ts
- tests/nylas.spec.ts
- tests/resources/attachments.spec.ts
- Add support for attachments api
[AV-2766](https://nylas.atlassian.net/browse/AV-2766)
[AV-2767](https://nylas.atlassian.net/browse/AV-2767)
[AV-2766]: https://nylas.atlassian.net/browse/AV-2766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AV-2767]: https://nylas.atlassian.net/browse/AV-2767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add support for attachments api

- CHANGELOG.md
- src/resources/messages.ts
The npm package `form-data` has an issue with importing compatibility between CJS and ESM. Using `import * as FormData` or `import FormData` works only on cjs while `import { default as FormData }` works only on esm. We work around this now by checking if `default` exists on the importing object, and using it if it does, otherwise just use `FormData`.
> Fix issue with form-data not importing correctly for ESM projects

- src/models/events.ts
- src/models/response.ts
- src/resources/calendars.ts
- src/resources/connectors.ts
- src/resources/credentials.ts
- src/resources/drafts.ts
- src/resources/events.ts
- src/resources/folders.ts
- src/resources/grants.ts
- src/resources/messages.ts
- src/resources/redirectUris.ts
- src/resources/threads.ts
- tests/resources/events.spec.ts
- Send RSVP support for Events API
[AV-2822](https://nylas.atlassian.net/browse/AV-2761)
[AV-2822]: https://nylas.atlassian.net/browse/AV-2822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Send RSVP support for Events API

- CHANGELOG.md
- src/models/event.ts
This PR remedies the issue seen where Graph accounts were returning 400 on update due to visibility field being present in the PUT request. We now check to see if the visibility field was modified, and only then do we include it in the outgoing request.
> Fix issue where Graph events were returning 400 on update

- CHANGELOG.md
- src/models/connectors.ts
- src/models/drafts.ts
Fix typing errors present in Connector and TrackingOptions
> Fix typing errors in TrackingOptions and Connector

- src/models/auth.ts
- src/resources/auth.ts
The code exchange response should include an email value as well.
Additionally, the provider detect endpoint was referencing the wrong path. Changed it to reflect the path mentioned here -> https://developer.nylas.com/docs/api/v3-beta/admin/#post-/v3/providers/detect
> Include email value for CodeExchange response

- src/models/event.ts
For [CUST-1790](https://nylas.atlassian.net/browse/CUST-1790), [our POST /send-rsvp docs](https://developer.nylas.com/docs/api/v2/#post-/send-rsvp) explicitly say that the `comment` param is optional. This PR changes the `comment` param to be optional.
[CUST-1790]: https://nylas.atlassian.net/browse/CUST-1790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CUST-1790: Make comment param in rsvp optional

- CHANGELOG.md
- src/models/auth.ts
- src/resources/auth.ts
- tests/resources/auth.spec.ts
clientSecret is not required if the API Key used for the SDK and the clientId belong to the same application. 
> Changed `clientSecret` to optional for token exchange methods; defaults to API Key now

- CHANGELOG.md
- src/models/auth.ts
- src/resources/auth.ts
- tests/resources/auth.spec.ts
This PR adds support for the /v3/connect/tokeninfo endpoint.
There are two methods that are part of the `Auth` resource that allow you to get information on a token; one for the ID token (`idTokenInfo`) and one for the access token (`accessTokenInfo`).
```ts
import Nylas, { TokenInfoResponse } from "nylas";
const nylas = new Nylas({
apiKey: 'nylas-api-key',
});
// Get information on an ID token
nylas.auth.idTokenInfo('idToken').then((response) => {
const idTokenInfo: TokenInfoResponse = response.data;
// ...
});
// Get information on an access token
nylas.auth.accessTokenInfo('accessToken').then((response) => {
const accessTokenInfo: TokenInfoResponse = response.data;
// ...
});
```
I confirm that this contribution is made under the terms of the MIT license and that I have the authority …
> Added support for /v3/connect/tokeninfo endpoint

- CHANGELOG.md
- src/models/events.ts
- src/models/webhooks.ts
- tests/resources/webhooks.spec.ts
This PR brings a couple of changes to the SDK models:
- Event-related models: `createdAt` and `updatedAt` are now optional fields
- Webhook-related models: `callbackUrl` renamed to `webhookUrl` to maintain consistency with the API
> Fix event and webhook models

- src/resources/messages.ts
This PR contains a small fix for including query params for message.find method, this allows message headers within the response.
https://nylas.atlassian.net/browse/TSDK-595?atlOrigin=eyJpIjoiOGUxOWZjYzRmOTYxNGMzMmE2NzdjMjcyMzNmYjcyNmEiLCJwIjoiaiJ9
> Include query params for message.find method

- CHANGELOG.md
- src/models/auth.ts
- src/models/availability.ts
- src/models/folders.ts
- tests/resources/auth.spec.ts
- tests/resources/folders.spec.ts
* Added support for `roundTo` field in availability response model
* Added support for `attributes` field in folder model
* Added support for icloud as an auth provider
* Removed clientId from detectProvider
> Added new fields

- CHANGELOG.md
- src/resources/drafts.ts
- src/resources/messages.ts
- tests/resources/drafts.spec.ts
- tests/resources/messages.spec.ts
This PR improves message send/draft create/update performance by always defaulting to application/json instead of multipart. Multipart will only be used for when a request contains a total attachments size of 3mb or higher.
> Improved message sending and draft create/update performance

- CHANGELOG.md
- src/models/availability.ts
- src/utils.ts
- tests/utils.spec.ts
We were not handling keys with digits in them well. Example; `roundTo30Minutes` was being converted to `round_to30_minutes` as opposed to `round_to_30_minutes` as expected.
> Fixed serialization/deserialization of keys with numbers in them

- src/models/events.ts
This PR updates the `type` property of the Date, Datespan, Time and Timespan types (the WhenTypes) to
`object` which is what is returned by the latest version (v3) of the Nylas api
Closes #550
> chore: change the type property of Date, Datespan, Time and Timespan to object

- src/apiClient.ts
- src/config.ts
- src/models/events.ts
- src/nylas.ts
- tests/apiClient.spec.ts
- tests/resources/applications.spec.ts
- tests/resources/attachments.spec.ts
- tests/resources/auth.spec.ts
- tests/resources/calendars.spec.ts
- tests/resources/contacts.spec.ts
- tests/resources/drafts.spec.ts
- tests/resources/events.spec.ts
- tests/resources/folders.spec.ts
- tests/resources/grants.spec.ts
- tests/resources/messages.spec.ts
- tests/resources/redirectUris.spec.ts
- tests/resources/smartCompose.spec.ts
- tests/resources/threads.spec.ts
- tests/resources/webhooks.spec.ts
This PR allows you to pass in a map of additional, custom headers that can be sent to the Node SDK.
This can be used one of two ways, for all outgoing calls or on a per-call-basis.
For all outgoing calls, you can set headers when initializing the Nylas SDK:
```js
const nylas = new Nylas({
apiKey: "NYLAS_API_KEY",
headers: {
foo: "bar"
},
});
messages = await nylas.messages.list({
"identifier",
}); // Will be sent with 'foo: bar' header
calendars = await nylas.calendars.list({
"identifier",
}); // Will be sent with 'foo: bar' header
```
For all calls to the API, we have an `override` object. This object is now extended to include a `headers` field.
```js
const nylas = new Nylas({
apiKey: "NYLAS_API_KEY",
});
messages = await nylas.messages.list({
"identifier",
overrides: {
headers: {
foo: …
```
> Add support for passing in headers to outgoing calls

- CHANGELOG.md
- src/models/drafts.ts
- tests/resources/drafts.spec.ts
This PR adds support to the custom headers field used to attach headers to message and draft objects. Not to be confused with custom headers to Nylas API requests, completed by #552.
> Add support for custom headers field for Drafts and Messages

- src/resources/auth.ts
- tests/resources/auth.spec.ts
Add support for include_grant_scopes=false on auth url generation. Currently include grant scopes is true by default and is not set to false if the user sets the variable as false - This fix should enable the user to do so
> Add support for include_grant_scopes=false on auth url generation

- CHANGELOG.md
- jest.config.js
- src/models/events.ts
- src/resources/events.ts
Send RSVP used to just return a `request_id` in the response, now it can return an error object in the event of a partial success where the send RSVP request is executed but the email was not sent.
> Add return type for send RSVP

- CHANGELOG.md
- src/models/auth.ts
This PR adds the `provider` field to the `CodeExchangeResponse` model.
> Add provider field to token exchange response

- src/models/messages.ts
- src/resources/messages.ts
- tests/resources/messages.spec.ts
This PR adds support for the `/messages/clean` endpoint.
> Add clean messages support

- CHANGELOG.md
- src/models/attachments.ts
- src/resources/drafts.ts
- src/resources/messages.ts
- src/utils.ts
- tests/resources/drafts.spec.ts
- tests/resources/messages.spec.ts
This PR fixes an issue where we were not encoding attachments less than 3mb properly. Furthermore, for `CreateAttachmentRequest` you may now provide your own base64 encoded string if you prefer to not have the SDK encode it.
> Fixed issue where attachments < 3mb were not being encoded correctly

- src/models/folders.ts
- src/resources/folders.ts
Adding ListFolderQuery Params to the folders endpoint
https://developer.nylas.com/docs/api/v3/ecc/#get-/v3/grants/-grant_id-/folders
> CUST-2556 - Adding list folders query params

- CHANGELOG.md
- src/apiClient.ts
- src/models/events.ts
- tests/apiClient.spec.ts
This PR adds support for filtering events by event type. Note that this feature is only for Google events.
> Added support for filtering by event type when listing events

- src/models/availability.ts
- tests/resources/calendars.spec.ts
- As per Nylas [documentation](https://developer.nylas.com/docs/api/v3/ecc/#post-/v3/calendars/availability), we support `collective` availability.
- In Node SDK we only support `max-availability` & `max-fairness` at this time.
- Add `collective` to `AvailabilityMethod`.
- Added unit test `getCollectiveAvailability`.
> Adding support for `collective` availability

- src/apiClient.ts
I encountered occasional application crashes and traced them back to timeouts coming from the Nylas API. After reviewing the Nylas-SDK, I found the culprit in the `setTimeout` call used to abort the request. It's bad practice to throw an error from `setTimeout` as its `try...catch` blocks will not intercept the error. Instead, these errors will crash the application.
`node-fetch` will reject when `controller.abort()` is called, so we don't need to throw from the timeout anyway.
Reference: 
https://jaketrent.com/post/catch-error-thrown-settimeout/
https://nodejs.org/dist/latest-v7.x/docs/api/errors.html#errors_node_js_style_callbacks
I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its …
> fix: application crash when timeout encountered

- CHANGELOG.md
- src/apiClient.ts
- tests/apiClient.spec.ts
This PR fixes an issue where the SDK was incorrectly modifying metadata objects before being sent to the API, specifically the metadata keys were being converted to snake case when they should remain unmodified.
> Fix issue where metadata was being incorrectly modified before being sent to the API

- CHANGELOG.md
- src/resources/auth.ts
Using `node:crypto` rather than `crypto` causes downstream issues for Jest integrations.
> Fix issue where crypto import was causing downstream Jest incompatibilities

- package.json
This package is currently leaking the `eslint-plugin-import` dev dependency into the production dependencies, thus requiring consumers to have it installed as a dependency.
> Remove eslint-plugin-import from production dependencies

- src/models/auth.ts
Since we support EWS as a provider for Custom Auth and Hosted Auth adding this value to our `Provider` type
> Add ews as a provider

- CHANGELOG.md
- src/models/events.ts
This PR adds the `attendees` field for filtering events.
> Add support for filtering events by attendee email

- CHANGELOG.md
- src/models/attachments.ts
This PR adds support for buffer type as a file attachment for attachments greater than 3MB and improves the messaging to the end user on when to use the different content types when attaching a file.
> Add buffer support for file attachments

- CHANGELOG.md
- src/resources/webhooks.ts
- tests/resources/webhooks.spec.ts
This PR fixes the rotate secret function to make a POST call rather than a PUT. Closes #583.
> Change rotate secret endpoint from being a PUT to a POST call

- CHANGELOG.md
- src/models/webhooks.ts
This PR updates the webhook trigger enum with new webhook triggers supported by the Nylas platform. Closes #582.
> Add new webhook trigger types

- CHANGELOG.md
- src/apiClient.ts
- src/resources/messages.ts
This PR fixes compatibility issues with ESM brought by the problematic form-data import statement. Fixes #576.
> Fix FormData import compatibility issues with ESM

- src/apiClient.ts
- tests/apiClient.spec.ts
> Adding gzip headers to reduce payload sizes and enable compression

- src/apiClient.ts
- tests/apiClient.spec.ts
- Reverts nylas/nylas-nodejs#591
- The HTTPClient used for NodeSDK includes the `"Accept-Encoding": "gzip"` by default, reverting this PR for now
> Revert "Adding gzip headers to reduce payload sizes and enable compression"

- CHANGELOG.md
- src/resources/webhooks.ts
- tests/resources/webhooks.spec.ts
The `webhooks.rotateSecret` method calls the incorrect URL, so all calls using this method fail with an error. This fixes that by switching the URL to the correct one. Closes #596. 
> Fix the ability to rotate webhook secrets

- src/apiClient.ts
- tests/apiClient.spec.ts
We were creating a new snakeCaseKey=item for each item in the value array.
This was creating multiple instances of the snakeCaseKey query param if there is more than one item in an array.
If more than one value was passing more than one value in an array query parameter we were generating a URL that looks like this:
`/v3/grants/9a8ce69e-61a5-42c5-bdda-1ab3c3745093/threads?limit=5&any_email=chase.w%40nylas.com&any_email=nick.b%40nylas.com`
This change makes it so that the above URL instead produces the following request URL:
`/v3/grants/9a8ce69e-61a5-42c5-bdda-1ab3c3745093/threads?limit=5&any_email=chase.w%40nylas.com,nick.b%40nylas.com`
I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of …
> Fix query parameters for array values

- CHANGELOG.md
- src/models/messages.ts
- src/models/threads.ts
- tests/resources/drafts.spec.ts
- Nylas API no longer return `created_at` field on message response (#573 )  - [Nylas Bug improvements](https://developer.nylas.com/docs/new/release-notes/2024-07-10-new-in-nylas/#nylas-api-bug-fixes-and-improvements)
- Therefore, removing them on the SDK.
- Change `latestMessageReceivedDate` & `latestMessageSentDate` to be optional on threads model.
> Remove `created_at` field from message model

- CHANGELOG.md
- package-lock.json
- src/apiClient.ts
- src/resources/threads.ts
- tests/apiClient.spec.ts
- tests/resources/threads.spec.ts
Fixes https://github.com/nylas/nylas-nodejs/issues/615 - looks like we introduced a regression in https://github.com/nylas/nylas-nodejs/pull/606.
I've reverted that PR because the proper way to pass an array of items for a single query param is to repeat the query param. 
Instead, I've added an override/transformation for the `threads.list` method that converts the `anyEmail` query param to a comma-separated list. I avoided putting this in `apiClient` because in my opinion, that's too disconnected from the resource where these overrides should occur.
> fix: transform anyEmail array into comma-delimited any_email parameter in threads list

- CHANGELOG.md
- src/apiClient.ts
- tests/apiClient.spec.ts
This pull request fixes an issue where the request timeout override provided in the request options was not being honored. The change ensures that if a custom timeout is specified, it is applied correctly when issuing requests, preventing them from running longer than intended.
> fix: respect timeout override when provided in request options

- CHANGELOG.md
- src/resources/messages.ts
- tests/resources/messages.spec.ts
fix: any_email was not transformed to a comma delimited list for messages.list, this was missed as part of https://github.com/nylas/nylas-nodejs/pull/618
> fix: any_email was not transformed to a comma delimited list for messages.list

- src/resources/grants.ts
- tests/resources/grants.spec.ts
List grants method did not follow the same syntax as our other methods, which could have been confusing. This PR fixes it so that the list method takes an object as the first param in which queryParam is an optional property.
> fix(grants): Support queryParams in list method first parameter

- CHANGELOG.md
- src/models/events.ts
- src/resources/events.ts
- tests/resources/events.spec.ts
This adds support for the new beta endpoint [GET /v3/grants/{grant_id}/events/import](https://developer.nylas.com/docs/api/v3/ecc/#get-/v3/grants/-grant_id-/events/import), which allows importing events from a calendar within a specified time frame. This is useful for applications that need to synchronize events with their own calendaring solution or enrich events with custom data.
> Add support for listImportEvents method to import events from calendars

- examples/notetakers/notetaker.ts
- src/models/notetakers.ts
- tests/resources/notetakers.spec.ts
> Updated to support the latest changes in the GET notetakers endpoint

- CHANGELOG.md
- src/resources/notetakers.ts
- tests/resources/notetakers.spec.ts
Fixes #638 - Adds the missing /cancel suffix to the Notetaker API endpoint that was introduced in v7.9.0
> fix: Add missing /cancel suffix in Notetaker API endpoint

- CHANGELOG.md
- src/models/auth.ts
- tests/resources/auth.spec.ts
- Add 'zoom' to Provider type in auth.ts to fix [#630](https://github.com/nylas/nylas-nodejs/issues/630)
- Add test to verify zoom provider support
> feat: add zoom as a supported provider type in Auth module

- CHANGELOG.md
- src/models/events.ts
The event status type in the Event interface was incorrectly using 'tentative' instead of 'maybe' as one of its possible values. This change updates the type to match the API documentation.
Changes:
- Update Status type to use 'maybe' instead of 'tentative'
- Update CHANGELOG.md
Fixes #626
> fix: update event status type to use 'maybe' instead of 'tentative'

- CHANGELOG.md
- examples/.env.example
- examples/README.md
- examples/messages/ENVIRONMENT.md
- examples/messages/README.md
- examples/messages/messages.ts
- examples/package.json
- package-lock.json
- src/models/messages.ts
- tests/resources/messages.spec.ts
- Added support for new message `fields` query parameter values: `include_tracking_options` and `raw_mime`
- Added support for `rawMime` property in Message responses when using `fields=raw_mime`
- feat: add message cleaning and scheduled messages examples
> feat(messages): add support for tracking_options, raw_mime fields and new MessageFields enum values

- CHANGELOG.md
- examples/folders/README.md
- examples/folders/folders.ts
- src/models/folders.ts
- tests/resources/folders.spec.ts
- feat: add support for includeHiddenFolders query parameter in folders list endpoint 
[TW-3960](https://nylas.atlassian.net/browse/TW-3960)
[TW-3960]: https://nylas.atlassian.net/browse/TW-3960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add support for includeHiddenFolders query parameter in folders list endpoint

- CHANGELOG.md
- examples/messages/README.md
- src/apiClient.ts
- src/models/response.ts
- tests/apiClient.spec.ts
- add tests for rawHeaders on responses
- update response models to include rawHeaders
- attach rawHeaders in API client without breaking equality
Addresses https://github.com/nylas/nylas-nodejs/issues/659
> feat(api): expose raw response headers on all responses via non-enumerable rawHeader

- CHANGELOG.md
- cjs-wrapper.d.ts
- cjs-wrapper.js
- examples/cjs-only/README.md
- examples/cjs-only/index.js
- examples/cjs-only/package-lock.json
- examples/cjs-only/package.json
- examples/cjs-only/utils/logger.js
- examples/edge-environment/package-lock.json
- package.json
- src/nylas.ts
- tsconfig.cjs.json
- tsconfig.json
> fix: resolve CJS build issue causing "TypeError: Nylas is not a constructor" error
